# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0001_initial'),
        ('cost_centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='تاريخ القيد')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='البيان')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('source_type', models.CharField(choices=[('manual', 'قيد يدوي'), ('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات')], default='manual', max_length=20, verbose_name='مصدر القيد')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounts.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('header_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_centers.costcenter', verbose_name='مركز تكلفة عام')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='الحساب')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_centers.costcenter', verbose_name='مركز التكلفة')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journalentry', verbose_name='القيد')),
            ],
        ),
    ]
