# Generated by Django 5.2.9 on 2026-07-20 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cost_centers', '0001_initial'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_no']},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_no',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='رقم القيد'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'entry_no'), name='uniq_journal_entry_no_per_company'),
        ),
    ]
