# Generated by Django 5.2.9 on 2026-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journalline_description_journalentry_entry_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المصدر'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'قيد يدوي'), ('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات')], default='manual', max_length=20, verbose_name='مصدر القيد'),
        ),
    ]
