# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0001_initial'),
        ('cost_centers', '0001_initial'),
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(blank=True, null=True, verbose_name='رقم السند')),
                ('party_type', models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('cost_center', 'مركز تكلفة'), ('other', 'أخرى')], default='customer', max_length=20, verbose_name='نوع الجهة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('draft', 'غير مرحل'), ('posted', 'مرحل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='البيان')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='accounting.account', verbose_name='حساب الصندوق / البنك')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_vouchers', to='accounts.company', verbose_name='الشركة')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='cost_centers.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='customers.customer', verbose_name='العميل')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_voucher', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('other_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers_other', to='accounting.account', verbose_name='حساب آخر')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='suppliers.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.receiptvoucher', verbose_name='سند القبض')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.salesinvoice', verbose_name='فاتورة البيع')),
            ],
            options={
                'verbose_name': 'تخصيص سند',
                'verbose_name_plural': 'تخصيصات السندات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(blank=True, null=True, verbose_name='رقم السند')),
                ('party_type', models.CharField(choices=[('supplier', 'مورد'), ('customer', 'عميل'), ('cost_center', 'مركز تكلفة'), ('other', 'أخرى')], default='supplier', max_length=20, verbose_name='نوع الجهة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('draft', 'غير مرحل'), ('posted', 'مرحل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='البيان')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='accounting.account', verbose_name='حساب الصندوق / البنك')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_vouchers', to='accounts.company', verbose_name='الشركة')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='cost_centers.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='customers.customer', verbose_name='العميل')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_voucher', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('other_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_other', to='accounting.account', verbose_name='حساب آخر')),
                ('reference_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='sales.salesinvoice', verbose_name='الفاتورة المرجعية')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='suppliers.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سند صرف',
                'verbose_name_plural': 'سندات الصرف',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'voucher_no'), name='uniq_payment_voucher_no_per_company')],
            },
        ),
        migrations.AddConstraint(
            model_name='receiptvoucher',
            constraint=models.UniqueConstraint(fields=('company', 'voucher_no'), name='uniq_receipt_voucher_no_per_company'),
        ),
    ]
