# Generated by Django 5.2.9 on 2025-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentvoucher_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'غير مرحل'), ('posted', 'مرحل'), ('cancelled', 'ملغى')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'غير مرحل'), ('posted', 'مرحل'), ('cancelled', 'ملغى')], default='draft', max_length=20),
        ),
    ]
