# Generated by Django 5.2.9 on 2026-07-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_is_payment_method'),
        ('accounts', '0001_initial'),
        ('payments', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_methods', to='accounts.company', verbose_name='الشركة'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_payment_method_per_company'),
        ),
    ]
