# Generated by Django 5.2.9 on 2025-12-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('cost_centers', '0002_alter_branch_options_alter_costcenter_options_and_more'),
        ('payments', '0003_paymentvoucher_status_receiptvoucher_status'),
        ('suppliers', '0003_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='cost_centers.costcenter'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='other_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_other', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='party_type',
            field=models.CharField(choices=[('supplier', 'مورد'), ('customer', 'عميل'), ('cost_center', 'مركز تكلفة'), ('other', 'أخرى')], default='supplier', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='cost_centers.costcenter'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='other_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers_other', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='party_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('cost_center', 'مركز تكلفة'), ('other', 'أخرى')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='suppliers.supplier'),
        ),
    ]
