# Generated by Django 5.2.9 on 2026-07-14 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentmethod_account_and_more'),
        ('pos', '0005_invoiceitem_discount_invoiceitem_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherallocation',
            name='pos_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='pos.invoice', verbose_name='فاتورة نقاط البيع'),
        ),
    ]
