# Generated by Django 5.2.8 on 2025-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='commercial_name',
            field=models.CharField(max_length=255, verbose_name='الاسم التجاري'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
    ]
