BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
 gettext(u'Point of Sale') 
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXXX XXX XXX XXX
    XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXX

        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Search product...') XX

        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Search invoice...') XX

        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            X  gettext(u'New Invoice') 
        XXXXXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX

            XXXX gettext(u'Categories') XXXXX

            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX

                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                     gettext(u'All') 
                XXXXXXXXX

                BBB BBB BB BBBBBBBBBB

                XXXX XXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX
                            XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXX XXXXX
                            XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXX

                    BB BBBBBBBBB
                    XXXX XXXXXX
                         XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX XXX X XXXX
                    BBBB
                    XXXX XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX XXX X XXXXXXXXXX
                    BBBBB

                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX

                XXXXXX

                BBBBBB

            XXXXXX

            XXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

                BBB B BB BBBBBBBB

                XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                     XXXXXXXXXX
                     XXXXXXXXXXXX
                     XXXXXXXXXXXXX
                     XXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBXX

                    XXXX XXXXXXXXXXX XXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXX

                        BB BBBBBBB
                        XXXX XXXXXX
                             XXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXX XXX X XXXX
                        BBBB
                        XXXX XXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXX XXX X XXXXXXXXXX
                        BBBBB

                        XXXX XXXXXXXXXXXXXXXX XXXXX

                            XXX XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX
                                
                            XXXXX

                            XX XXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                  gettext(u'SAR') 
                            XXXX

                            XXXXXX XXXXXXXXXXXXXXXXXXX
                                 gettext(u'Stock') X 
                            XXXXXXXX

                        XXXXXX

                    XXXXXX

                XXXXXX

                BBBBBB

            XXXXXX

        XXXXXX

        XXXX XXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXX XXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX

    XXXXXX

XXXXXX

XXXXXXXX

XXX XXXXXXXX X XXX
XXX XXXXXXXXXXXXXXX X XXXXX
XXX XXXXXXXXXXXXXX X XX


XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXX

    XXXXX XX X XXXXXXXXXXXXXXXXX

    XXXXXXXXXXXX X X
        XXXXXX XXX
        XXXXXX XX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XX
    XX

    XXXXX XXXXX X XXXX XX X gettext(u'Invoice') XX

    XX XXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXXXXXXXXXXX X X
        XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XX

    XXXXXXXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXX

    XXXXXXXXXXXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXX X XXXXXXX

    XXXXXXXXXXXXXXXXX X X

        XXXX XXXXXXXXXXXXX

            XXXXXXX gettext(u'Select Customer') XXXXXXXX

            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

                XXXXXXX XXXXXXXXX
                     gettext(u'Cash Customer') 
                XXXXXXXXX

                BBB BBBB BB BBBBBBBBB
                XXXXXXX XXXXXXXXX
                    
                XXXXXXXXX
                BBBBBB

            XXXXXXXXX

        XXXXXX

        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX

            XXXXXXX
                XXXX
                    XXXX gettext(u'Item') XXXXX
                    XXXX gettext(u'Qty') XXXXX
                    XXXX gettext(u'Price') XXXXX
                    XXXX gettext(u'Total') XXXXX
                    XXXXXXXXXX
                XXXXX
            XXXXXXXX

            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXX
                XXXX
                    XXX XXXXXXXXXXXX
                         gettext(u'Grand Total') 
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXXXXXXX

                    XXXXXXXXX
                XXXXX
            XXXXXXXX

        XXXXXXXX

        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX
            X  gettext(u'Save & Proceed to Payment') 
        XXXXXXXXX
    XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX XXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXX X XXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
        XXXXXXXXXXXXXXX X XXXXX
    X
X


XX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXX

        XXXXXXX gettext(u'Open invoice first') XXX

        XXXXXXX
    X

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXX

    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXX XXXX
    XXXXXXXXXXXXXXXXXXXX

        XXX XXXXXXXXXXXXX X XXXXXX

        XX XXXXX XXXXX
        XXXXXXXX XX XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXXXXXXXX X XXXXXXXX
                    X gettext(u'Stock is lower than requested quantity for product')  XXXXXXXXXXXX gettext(u'Allow negative stock?') X
                XX

                XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                X

                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX

                XXXXXXXXXXXXX X XXXXX
            X
        X

        XXXXXXXXXXXXXX X X
            XXXXX XXXXX
            XXXXXX XXXXXX
            XXXX XX
            XXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX

    XXXXXX

        XXXXX XXXX X XXXXXXXXXXXXXXX

        XX XXXXXX XXXXX
        XXXXXXXXXXX X X X XXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXXXXXXXX X XXXXXXXX
                    X gettext(u'Stock is lower than requested quantity for product')  XXXXXXXXXXXX gettext(u'Allow negative stock?') X
                XX

                XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                X

                XXXXXXXXXXXXXXXXXX X XXXXX
            X
        X

        XXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXX

    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XX

    XXXXXXXXXXXXXXX X XXX

    XXX XXXXX X XX

    XXXXXXX XXX XX XXXXXXXXXXX

        XXXXX XXXX X XXXXXXXXXXXXXXX

        XXXXX XXXXXXXXX X XXXXXXXX X XXXXXXXXXXX

        XXXXX XX XXXXXXXXXX

        XXXXXXXXXXXXXXX XX X

            XXXX

                XXXXXXXXXXXXXXXXXXXXX

                XXXX

                    XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
                        X
                    XXXXXXXXX

                    XXXXXXXXXXX

                    XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX
                        X
                    XXXXXXXXX

                XXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX

                    XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        X
                    XXXXXXXXX

                XXXXX

            XXXXX
        XX
    X

    XXXXXXXXX X XXXXXX

    XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXXXXXXXXXXXXXXXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XX XXXXXX

    XXXXXXXXXXX XX XXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXX

    XXXXX XXXXX X XXX

    XXXXXXX XXX XX XXXXXXXXXXX

        XXXXXXXXXXXX
            XXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXX
    X

    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX X

        XXXXXXX XXXXXXX

        XXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX
        XX

        XXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXX
        XX

    XX

    XXXXXXXXX XX XXXXXXXXXXX

    XXXXXXXXXX XX X

        XXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX

            XXXXXXXXXXXXXXXX XX XXXXXXXXX
        X
    XX

    XXXXXXXXXX XX X

        XXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXX XXXXXXXX
    XXX
X


XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X

            XXXXXXXXXXXXX XXX XXXX

                XXXXXXXXXXXXXXXXXX X XXXXXXXX

            XXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX

                    XXXXXXXXXXXXXXXXXX X XXXXXXXX

                XXXXXX

                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            X
        XXX
    XXX
XXX


XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X

            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

            XXXXXX

                XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        XXX
    XXX
XXX


XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
XXX


XX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

    XXXXXXXXXXXXXXXX
XXX


XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX

XXXXXXXXX

BBBBBBBB