BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXX

            BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXX XXXXXXXX XX XXXX XXXXXX XXX XXXXX
                XXXXXX
            BBBBB

            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB

                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX
                           XXXXXXXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXXX
                           XXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX
                           XXXXXXXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXXX
                           XXXXXXXXX
                XXXXXX

                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXX
                XXXXXXXXX
            XXXXXXX

        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
