BBBB BBBB

BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Edit Account') XXXXX

XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB

    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Account Name') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Code') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
         gettext(u'Cancel') 
    XXXX

XXXXXXX

BBBBBBBB