BBBB BBBB

BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

XXX XXXXXXXXXXXXXX XXXXXX gettext(u'View Account') XXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXX
        XXXX gettext(u'Name') XXXXX
        XXXXXXXXX
    XXXXX

    XXXX
        XXXX gettext(u'Code') XXXXX
        XXXXXXXXX
    XXXXX

    XXXX
        XXXX gettext(u'Type') XXXXX
        XXXXXXXXX
    XXXXX

    XXXX
        XXXX gettext(u'Nature') XXXXX
        XXXXXXXXX
    XXXXX

XXXXXXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
     gettext(u'Back to Tree') 
XXXX

XXXX

XXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX gettext(u'Child Accounts') XXXXX

BB BBBBBBBB
    BBB BBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXXX

            XXXXX
                XXXXXXXXXXXXXXXXX X 
            XXXXXX

            XXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX
                   XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                     gettext(u'View') 
                XXXX
            XXXXXX

        XXXXXX
    BBBBBB
BBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'No child accounts') 
    XXXXXX
BBBBB

BBBBBBBB