BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXX XXXXX XXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
            X XXXXX XXXX XXXXX
        XXXX
    XXXXXX

    BB BBBBB
        XXX XXXXXXXXXXXXXXXXXX
            BBB BB BB BBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBB
            BBBBBB
        XXXXX
    BBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXX XXXXX XXXXX XXX
        XXXXXX
    BBBBB

XXXXXX

XXXX XXXXXXXXXXXXXXXXXX XX XXX X XXXXX XXXXXXXXXXXXXXXXXX XXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXX X
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXX
    X
X
XXXXXXXXX

XXXXXXX
XX XXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XX
XXXXXXXXXXX
XXXXXXXXXX XX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXX XXX XX
X

XXXXXXX X
    XXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXX XXXXX
X

XXXXXXXXXX X
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXX
X
XXXXXXXX

BBBBBBBB
