# Generated by Django 5.2.9 on 2026-07-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المتجر')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='stores/favicon/', verbose_name='أيقونة المتجر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المتجر')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_store', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'متجر إلكتروني',
                'verbose_name_plural': 'المتاجر الإلكترونية',
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('banner', 'بانر'), ('category', 'تصنيفات'), ('products', 'منتجات'), ('text', 'نص')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/home/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sections', to='ecommerce.store')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='الدومين')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ecommerce.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_guest_checkout', models.BooleanField(default=True, verbose_name='السماح بالشراء كزائر')),
                ('show_stock', models.BooleanField(default=True, verbose_name='إظهار المخزون')),
                ('enable_reviews', models.BooleanField(default=True, verbose_name='تفعيل التقييمات')),
                ('enable_wishlist', models.BooleanField(default=True, verbose_name='تفعيل المفضلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ecommerce.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', max_length=20)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=20)),
                ('font_family', models.CharField(default='Tahoma', max_length=100)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='ecommerce.store')),
            ],
        ),
    ]
