# Generated by Django 5.2.9 on 2026-07-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='top_bar_enabled',
            field=models.BooleanField(default=True, verbose_name='إظهار الشريط العلوي'),
        ),
        migrations.AddField(
            model_name='store',
            name='top_bar_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='رسالة الشريط العلوي'),
        ),
    ]
