# Generated by Django 5.2.9 on 2026-07-21 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecommerce', '0006_store_top_bar_enabled_store_top_bar_text'),
        ('products', '0002_productattribute_attributevalue_productimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سلة مشتريات', 'verbose_name_plural': 'سلال المشتريات'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'store')},
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العلامة التجارية')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='الرابط')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_brands', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/store/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='النص البديل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_main', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_images', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
