# Generated by Django 5.2.9 on 2026-07-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_storenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_notifications', to='ecommerce.order'),
        ),
    ]
