# Generated by Django 5.2.9 on 2026-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_order_created_at_alter_order_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='إيصال التحويل'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم صاحب الحساب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح بوابة الدفع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بوابة الدفع'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان'),
        ),
    ]
