# Generated by Django 5.2.9 on 2026-07-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_payment_receipt_paymentmethod_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='building_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم المبنى'),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='store',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='store',
            name='google_map_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط خرائط Google'),
        ),
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='store',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='الشارع'),
        ),
        migrations.AddField(
            model_name='store',
            name='unit_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الوحدة'),
        ),
    ]
