# Generated by Django 5.2.9 on 2026-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_store_building_no_store_city_store_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='store',
            name='building_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم المبنى'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='store',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='store',
            name='google_map_url',
            field=models.URLField(blank=True, default='', verbose_name='رابط خرائط Google'),
        ),
        migrations.AlterField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='store',
            name='unit_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الوحدة'),
        ),
    ]
