# Generated by Django 5.2.9 on 2026-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_store_address_alter_store_building_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_publishable_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المفتاح القابل للنشر'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المفتاح السري'),
        ),
    ]
