# Generated by Django 5.2.9 on 2026-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_paymentmethod_gateway_publishable_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='gateway_key',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway_name',
            field=models.CharField(blank=True, help_text='مثال: moyasar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway_publishable_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publishable Key'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
