# Generated by Django 5.2.9 on 2026-07-30 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecommerce', '0018_remove_payment_notes_remove_payment_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('cart_snapshot', models.JSONField(verbose_name='نسخة السلة')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='accounts.company', verbose_name='الشركة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='ecommerce.paymentmethod', verbose_name='طريقة الدفع')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='ecommerce.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'نية دفع',
                'verbose_name_plural': 'نيات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
