# Generated by Django 5.2.9 on 2026-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_paymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='bank_receipts/', verbose_name='صورة التحويل البنكي'),
        ),
    ]
