# Generated by Django 5.2.9 on 2026-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_order_bank_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('bank_transfer', 'تحويل بنكي - بانتظار المراجعة'), ('paid', 'مدفوع'), ('partial', 'دفع جزئي'), ('refunded', 'مسترجع')], db_index=True, default='unpaid', max_length=20, verbose_name='حالة الدفع'),
        ),
    ]
