# Generated by Django 5.2.9 on 2026-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('cash_on_delivery', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي - بانتظار المراجعة'), ('paid', 'مدفوع'), ('partial', 'دفع جزئي'), ('refunded', 'مسترجع')], db_index=True, default='unpaid', max_length=20, verbose_name='حالة الدفع'),
        ),
    ]
