# Generated by Django 5.2.9 on 2026-08-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_order_payment_status'),
        ('products', '0005_stockmovement_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'منتج المتجر', 'verbose_name_plural': 'منتجات المتجر'},
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب المنتجات المميزة'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='منتج مميز'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='وصل حديثًا'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_offer',
            field=models.BooleanField(default=False, verbose_name='ضمن العروض'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='new_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب وصل حديثًا'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='offer_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العروض'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_store_links', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='ecommerce.store', verbose_name='المتجر'),
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر في المتجر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_store_categories', to='products.category', verbose_name='التصنيف')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='ecommerce.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'تصنيف المتجر',
                'verbose_name_plural': 'تصنيفات المتجر',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('store', 'category')},
            },
        ),
    ]
