# Generated by Django 5.2.9 on 2026-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_alter_storeproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر العرض'),
        ),
    ]
