# Generated by Django 5.2.9 on 2026-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_storeproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('cash_on_delivery', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي - '), ('paid', 'مدفوع'), ('partial', 'دفع جزئي'), ('refunded', 'مسترجع')], db_index=True, default='unpaid', max_length=20, verbose_name='حالة الدفع'),
        ),
    ]
