# Generated by Django 5.2.9 on 2026-08-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='سعر التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('cash_on_delivery', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي  '), ('paid', 'مدفوع'), ('partial', 'دفع جزئي'), ('refunded', 'مسترجع')], db_index=True, default='unpaid', max_length=20, verbose_name='حالة الدفع'),
        ),
    ]
