# Generated by Django 5.2.9 on 2026-08-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_store_shipping_cost_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('shipping', 'سياسة الشحن'), ('return', 'سياسة الاسترجاع'), ('terms', 'الشروط والأحكام'), ('privacy', 'سياسة الخصوصية')], max_length=20, verbose_name='نوع السياسة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان السياسة')),
                ('content', models.TextField(blank=True, verbose_name='محتوى السياسة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='ecommerce.store', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'سياسة متجر',
                'verbose_name_plural': 'سياسات المتجر',
                'constraints': [models.UniqueConstraint(fields=('store', 'policy_type'), name='unique_store_policy')],
            },
        ),
    ]
