# Generated by Django 5.2.9 on 2026-08-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_storepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='privacy_policy',
            field=models.TextField(blank=True, default='', verbose_name='سياسة الخصوصية'),
        ),
        migrations.AddField(
            model_name='store',
            name='return_policy',
            field=models.TextField(blank=True, default='', verbose_name='سياسة الاسترجاع'),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_policy',
            field=models.TextField(blank=True, default='', verbose_name='سياسة الشحن'),
        ),
        migrations.AddField(
            model_name='store',
            name='terms_policy',
            field=models.TextField(blank=True, default='', verbose_name='الشروط والأحكام'),
        ),
    ]
