# Generated by Django 5.2.9 on 2026-08-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_store_privacy_policy_store_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط إنستغرام'),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط X'),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط واتساب'),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب'),
        ),
    ]
