from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce",
            "0031_remove_store_privacy_policy_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="store",
                    name="privacy_policy",
                ),
                migrations.RemoveField(
                    model_name="store",
                    name="return_policy",
                ),
                migrations.RemoveField(
                    model_name="store",
                    name="shipping_policy",
                ),
                migrations.RemoveField(
                    model_name="store",
                    name="terms_policy",
                ),

                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="address",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="building_no",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="city",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="country",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="district",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="facebook_url",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="google_map_url",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="instagram_url",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="postal_code",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="privacy_policy",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="return_policy",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="shipping_policy",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="street",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="terms_policy",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="top_bar_enabled",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="top_bar_text",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="twitter_url",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="unit_no",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="whatsapp_url",
                ),
                migrations.RemoveField(
                    model_name="storeannouncement",
                    name="youtube_url",
                ),
            ],
        ),
    ]