# Generated by Django 5.2.9 on 2026-09-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_entry_no_and_more'),
        ('accounts', '0001_initial'),
        ('ecommerce', '0032_remove_store_privacy_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store_customer_account', to='accounting.account', verbose_name='الحساب المحاسبي')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_customer_accounts', to='accounts.company', verbose_name='الشركة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_customer_accounts', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حساب عميل متجر',
                'verbose_name_plural': 'حسابات عملاء المتجر',
                'constraints': [models.UniqueConstraint(fields=('customer', 'company'), name='unique_store_customer_account_per_company')],
            },
        ),
    ]
