BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXXXXX
XX XXXXXXX XXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXX XXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXX
    XXXXXXX XXXXX
X

XX XXXXX XXXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XX XXXXXX XX
XXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
X

XX XXXXX XXXXX XX
XXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X

XX XXXXXX XX
XXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX XXX XXXXX XXXXXXXX
X

XXXXXXXXX XX X
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXX XXXX XXXX XX XXXXXXXX XXXXXXXXXXXXXX

    XXXX X XXXX XXXX XXX XXX
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXXXXXXX

            XXXX XXXXXXXXXX XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXXXX XXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXX XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXX XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                           XXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                           XXXXXXXXX
                XXXXXX

            XXXXXX
        XXXXXX

        XXXX XX XXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
        XXXXXX

    XXXXXXX
    XXXX X XXXX XXXXX XXX XXX

XXXXXX

BBBBBBBB
