BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
X

XX XXXXXX XXXXXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXX XXXXXXXX
X
XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X

XX XXXXX XXXXXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XX XXXXXXX XXXX XXX XXXXXXXX XX
XXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
X
XXXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXX

        XXXX XXXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX XXXXXX X XXXXXX X XXXXXXX X XXXXX XXXXXXXXXXXX
                XXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXX X XXXXXX XXXXXX X XXXXXXXXXXXXXX
                XXXXXX
            XXXX
        XXXXXX

        XXXX XXXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXX X XXXXXXX X XXXXX XXXXXXXXX X XXXXXXXXXXXX
                XXXXXX
            XXXX
        XXXXXX

    XXXXXX

XXXXXX

BBBBBBBB
