BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'إعدادات النظام') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX gettext(u'إعدادات النظام') XXXXX

    XXX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'الإعدادات العامة') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'إعدادات الطباعة') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'النسخ الاحتياطي') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'إعدادات متقدمة') XXXX
        XXXXX
    XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'اللغة الافتراضية للنظام') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'تنسيق التاريخ') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'نمط الألوان') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'الوضع الفاتح') XX
            XXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXX gettext(u'حفظ الإعدادات') XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
            XXX gettext(u'هنا يمكنك ضبط إعدادات الطباعة.') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
            XXX gettext(u'هنا يمكنك إعداد النسخ الاحتياطي التلقائي.') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
            XXX gettext(u'خيارات متقدمة لإعداد النظام.') XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
