BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
X

XXXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXX X XX
X

XXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXX XXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
X

XX XX XXXXX XXX XX XXXXXXXX XX
XXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXX XXXX XXXXXXXXXXX
    XXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXX XXX
        XXX XXXXXXXXXX XXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX
        XXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX

            XXXX XXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX

                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB

                    XXXX XXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX

            XXXXXX

            XXXX XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX

                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                    XXXXXX

                XXXXXXX

            XXXXXX

        XXXXXX

    XXXXXX

XXXXXX

BBBBBBBB
