# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cost_centers', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_po', models.BooleanField(default=False, verbose_name='أمر شراء')),
                ('invoice_no', models.IntegerField()),
                ('date_invoice', models.DateField()),
                ('date_issue', models.DateField()),
                ('date_delivery', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='accounts.company', verbose_name='الشركة')),
                ('header_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='cost_centers.costcenter')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='cost_centers.costcenter')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.IntegerField(blank=True, null=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='accounts.company', verbose_name='الشركة')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='purchase.purchaseinvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchasereturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_no', 'is_po'), name='purchase_uniq_invoice_no_per_company_and_type'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('company', 'return_no'), name='purchase_uniq_return_no_per_company'),
        ),
    ]
