# Generated by Django 5.2.9 on 2026-08-01 11:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً'), ('paid', 'مدفوعة')], default='unpaid', max_length=20),
        ),
    ]
