# Generated by Django 5.2.9 on 2026-01-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_total_purchaseitem_tax_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
