BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXXXXX
    XXXXXX XXXXX XX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXX XX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXX
    X
    XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXX XXXXX
    X
    XXXXX XX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXX

    XXXX X XXXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                XXX XXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXX
                XXXXX

                XXXX X XXXXX XXXX XXXXXX XXX
                XXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXXXXX

            XXXXXXX
                BBB BBB BB BBBB
                XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXXXX
                BBBBB
                XXXX
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
                XXXXX
                BBBBBB
            XXXXXXXX

            XXXXXXX
                XXXX
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXXXX
            XXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX

    XXXXXXXXXXXXXXXX XX X
        XXX XXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXX X XXXXXXXXXXXXXXXXXXXX
            XX XXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXX X XXXXXX
            X
        XXX
        XXXXXXXXXXXXXXXXX X XXXX X XX X XXXXXXX
    XXX
X
XXXXXXXXX

BBBBBBBB
