BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXXX XXXXX XXXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX

XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXX

XXXXX XXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXX

BB BBBBBBBBB BBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX
    XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX
    XXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX
XXXXXXXX
XXXXXXX

XXXX
    XXXXXXXXXX XXXXXXXXXXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFF
        XXXX
    XXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFF
        XXXX
    XXXXX
XXXXX

XXXX
    XXXXXXXXXXX XXXXXXXXXXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XFFFFFFFFX
        XXXX
    XXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XFFFFFFFFX
        XXXX
    XXXXX
XXXXX

XXXX
    XXXXXXXXX XX XXXX XXXXXXXXXX
    XXXXXXXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFF
        XXXX
    XXXXX
XXXXX

XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXFFFFFFFFXXXXX
XXXXX

XXXXXXXX
XXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX
    XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX
    XXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX
XXXXXXXX
XXXXXXX

XXXX
    XXXXXXXXXX XXXXXXXXXXXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFF
        XXXX
    XXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFF
        XXXX
    XXXXX
XXXXX

XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XFFFFFFFFX
        XXXX
    XXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XFFFFFFFFX
        XXXX
    XXXXX
XXXXX

XXXX
    XXXXXXXXX XX XXXX XXXXXXXXXX
    XXXXXXXXXX
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFF
        XXXX
    XXXXX
XXXXX

XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXX XXXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXFFFFFFFFXXXXX
XXXXX

XXXXXXXX
XXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX XXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
XXXXXXX
XXX XXXXXXXXXXXXXXXX
    XXXXXXXX XXXXX XXXXXX XXXXXXXXXXXX
    XXXXFFFFFFFFXXXXX
XXXXX
XXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXX XX XXXXXXX XXXXXXXXXXXX
    XXXXFFFFFFFFXXXXX
XXXXX
XXXXXXXX
XXXXXXXX
XXXXXX

BBBBB

XXXXXX
BBBBBBBB
