BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX

XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
    XXXXX XXXXXX XXXXXX XXXXXX XXXXXXX XXX XXXXXX
XXXXX

XXXXX XXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXX

BB BBBBBBBBB BBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX
XXXXX
XXXXXXXX
XXXXXXX
BBB BBB BB BBBBBBBBBB
XXXX
    XXXXXXXXXX
    XXXXFFFFFFFFXXXXX
    XXXXFFFFFFFFXXXXX
    XXXXFFFFFFFFXXXXX
XXXXX
BBBBB
XXXX
    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
XXXXX
BBBBBB
XXXXXXXX
XXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXX
XXXXX
XXXXXXXX
XXXXXXX
BBB BBB BB BBBBBBBBBBBBB
XXXX
    XXXXXXXXXX
    XXXXFFFFFFFFXXXXX
    XXXXFFFFFFFFXXXXX
    XXXXFFFFFFFFXXXXX
XXXXX
BBBBB
XXXX
    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
XXXXX
BBBBBB
XXXXXXXX
XXXXXXXX
XXXXXX

BBBBB

XXXXXX
BBBBBBBB
