# Generated by Django 5.2.9 on 2026-08-04 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_branches', to='accounts.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_departments', to='accounts.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('first_name_ar', models.CharField(max_length=50)),
                ('last_name_ar', models.CharField(blank=True, max_length=50)),
                ('first_name_en', models.CharField(max_length=50)),
                ('last_name_en', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('ذكر', 'Male'), ('أنثى', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID')),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('probation_days', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('employee_type', models.CharField(default='Full-time Employee', max_length=50)),
                ('use_user_account', models.BooleanField(default=False, verbose_name='This employee uses a login account')),
                ('annual_leave_entitlement', models.IntegerField(default=0, verbose_name='Annual Leave Entitlement')),
                ('current_annual_leave', models.IntegerField(default=0, verbose_name='Current Annual Leave')),
                ('compensatory_leave', models.IntegerField(default=0, verbose_name='Compensatory Leave')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Employee Photo')),
                ('national_id_file', models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='National ID File')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport Number')),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='Passport File')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='Contract File')),
                ('other_files', models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='Other Files')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_employees', to='accounts.company', verbose_name='Company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_evaluations', to='accounts.company', verbose_name='Company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evaluation_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_evaluation_attachments', to='accounts.company')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('criteria_type', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_criteria', to='accounts.company', verbose_name='Company')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='hr.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_targets', to='accounts.company', verbose_name='Company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='hr.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('peer', 'Peer'), ('manager', 'Manager')], default='peer', max_length=20)),
                ('value', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='evaluation_scores/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_scores', to='accounts.company', verbose_name='Company')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.evaluationcriteria')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_scores', to='hr.employee')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hr.evaluationtarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_evaluation_types', to='accounts.company', verbose_name='Company')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.evaluationtype'),
        ),
        migrations.CreateModel(
            name='HRPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_view', models.BooleanField(default=True, verbose_name='View Employees')),
                ('employees_add', models.BooleanField(default=True, verbose_name='Add Employee')),
                ('employees_edit', models.BooleanField(default=True, verbose_name='Edit Employee')),
                ('employees_delete', models.BooleanField(default=True, verbose_name='Delete Employee')),
                ('employees_export', models.BooleanField(default=True, verbose_name='Export Employees')),
                ('employees_view_all_departments', models.BooleanField(default=True, verbose_name='View All Departments or Own Department Only')),
                ('departments_view', models.BooleanField(default=True, verbose_name='View Departments')),
                ('departments_add', models.BooleanField(default=True, verbose_name='Add Department')),
                ('departments_edit', models.BooleanField(default=True, verbose_name='Edit Department')),
                ('departments_delete', models.BooleanField(default=True, verbose_name='Delete Department')),
                ('worklocations_view', models.BooleanField(default=True, verbose_name='View Work Locations')),
                ('worklocations_add', models.BooleanField(default=True, verbose_name='Add Work Location')),
                ('worklocations_edit', models.BooleanField(default=True, verbose_name='Edit Work Location')),
                ('worklocations_delete', models.BooleanField(default=True, verbose_name='Delete Work Location')),
                ('attendance_view', models.BooleanField(default=True, verbose_name='View Attendance')),
                ('attendance_check', models.BooleanField(default=True, verbose_name='Check In/Out')),
                ('attendance_edit', models.BooleanField(default=True, verbose_name='Edit Attendance')),
                ('attendance_approve', models.BooleanField(default=True, verbose_name='Approve Attendance')),
                ('attendance_view_all_departments', models.BooleanField(default=True, verbose_name='View Attendance for Own Department or All')),
                ('leaves_view', models.BooleanField(default=True, verbose_name='View Leaves')),
                ('leaves_add', models.BooleanField(default=True, verbose_name='Submit Leave')),
                ('leaves_approve', models.BooleanField(default=True, verbose_name='Approve Leave')),
                ('leaves_reject', models.BooleanField(default=True, verbose_name='Reject Leave')),
                ('leaves_view_all_departments', models.BooleanField(default=True, verbose_name='View Leaves for Own Department or All')),
                ('evaluations_view', models.BooleanField(default=True, verbose_name='View Evaluations')),
                ('evaluations_add', models.BooleanField(default=True, verbose_name='Create Evaluation')),
                ('evaluations_edit', models.BooleanField(default=True, verbose_name='Edit Evaluation')),
                ('evaluations_delete', models.BooleanField(default=True, verbose_name='Delete Evaluation')),
                ('evaluations_peer', models.BooleanField(default=True, verbose_name='Evaluate as Peer')),
                ('evaluations_manager', models.BooleanField(default=True, verbose_name='Evaluate as Manager')),
                ('evaluations_approve', models.BooleanField(default=True, verbose_name='Approve Results')),
                ('evaluations_reports', models.BooleanField(default=True, verbose_name='View Evaluation Reports')),
                ('payroll_view', models.BooleanField(default=True, verbose_name='View Payroll')),
                ('payroll_add', models.BooleanField(default=True, verbose_name='Create Payroll')),
                ('payroll_edit', models.BooleanField(default=True, verbose_name='Edit Payroll')),
                ('payroll_delete', models.BooleanField(default=True, verbose_name='Delete Payroll')),
                ('payroll_approve', models.BooleanField(default=True, verbose_name='Approve Salary Payment')),
                ('reports_view', models.BooleanField(default=True, verbose_name='View Reports')),
                ('reports_export', models.BooleanField(default=True, verbose_name='Export PDF / Excel')),
                ('reports_view_all_departments', models.BooleanField(default=True, verbose_name='View Reports for Own Department or Entire Company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_permissions', to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Permission',
                'verbose_name_plural': 'HR Permissions',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('compensatory', 'Compensatory Leave'), ('other', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_leaves', to='accounts.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_payrolls', to='accounts.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100, verbose_name='Shift Name')),
                ('shift_order', models.PositiveIntegerField(verbose_name='Shift Order')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Break Start Time')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Break End Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_shifts', to='accounts.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['shift_order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_schedules', to='accounts.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.shift')),
            ],
            options={
                'ordering': ['date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Check In Time')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check Out Time')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Late Minutes')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=10, verbose_name='Status')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance', to='accounts.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='Employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('building_no', models.CharField(blank=True, max_length=30)),
                ('unit_no', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('google_map_url', models.URLField(blank=True, max_length=1500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('allowed_radius', models.PositiveIntegerField(blank=True, default=100, help_text='Allowed radius in meters')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_work_locations', to='accounts.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.worklocation', verbose_name='Work Location'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='hr_uniq_branch_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='hr_uniq_department_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='evaluationscore',
            constraint=models.UniqueConstraint(fields=('company', 'target', 'criteria', 'evaluator', 'role'), name='hr_uniq_score_per_company'),
        ),
        migrations.AddConstraint(
            model_name='evaluationtype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='hr_uniq_evaltype_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='hrpermission',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_hr_permission_per_company_user'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('company', 'shift_order'), name='hr_uniq_shift_order_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'date'), name='hr_uniq_schedule_per_company'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'date'), name='hr_uniq_attendance_per_company'),
        ),
        migrations.AddConstraint(
            model_name='worklocation',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='hr_uniq_work_location_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_number'), name='hr_uniq_employee_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='hr_uniq_employee_email_per_company'),
        ),
    ]
