# Generated by Django 5.2.9 on 2026-01-14 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='hrreport',
            name='file',
        ),
        migrations.RemoveField(
            model_name='hrreport',
            name='title',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='clothing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل لبس'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='عقد العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name_ar',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الاسم بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name_en',
            field=models.CharField(default='Not set', max_length=100, verbose_name='الاسم بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='Not set', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل سكن'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب/عزباء'), ('married', 'متزوج/متزوجة')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='صورة الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدلات أخرى'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='وثائق أخرى'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل ترحيل'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hrreport',
            name='name',
            field=models.CharField(default='غير محدد', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'سنوية'), ('sick', 'مرضية'), ('other', 'أخرى')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='clothing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch'),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
