# Generated by Django 5.2.9 on 2026-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_evaluation_notes_evaluationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationscore',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='evaluation_scores/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
