# Generated by Django 5.2.9 on 2026-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Basic Salary'),
        ),
    ]
