# Generated by Django 5.2.9 on 2026-01-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_evaluation_employee_delete_hrreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.FloatField(default=0, verbose_name='الإجازة السنوية الحالية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_entitlement',
            field=models.FloatField(default=0, verbose_name='الإجازة السنوية المستحقة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='compensatory_leave',
            field=models.FloatField(default=0, verbose_name='الإجازات التعويضية'),
        ),
    ]
