# Generated by Django 5.2.9 on 2026-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clothing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Clothing Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Housing Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other Allowances'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transport Allowance'),
        ),
    ]
