# Generated by Django 5.2.9 on 2026-08-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0003_evaluationscore_attachment_evaluationscore_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('allowed_radius', models.PositiveIntegerField(default=100, help_text='Allowed radius in meters')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_work_locations', to='accounts.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.worklocation', verbose_name='Work Location'),
        ),
        migrations.AddConstraint(
            model_name='worklocation',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='hr_uniq_work_location_per_company'),
        ),
    ]
