# Generated by Django 5.2.9 on 2026-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_worklocation_employee_work_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
