# Generated by Django 5.2.9 on 2026-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_annual_leave_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='annual_leave_balance',
        ),
        migrations.AddField(
            model_name='employee',
            name='current_annual_leave',
            field=models.IntegerField(default=0, verbose_name='الإجازة السنوية الحالية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_entitlement',
            field=models.IntegerField(default=0, verbose_name='الإجازة السنوية المستحقة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='compensatory_leave',
            field=models.IntegerField(default=0, verbose_name='الإجازات التعويضية'),
        ),
    ]
