# Generated by Django 5.2.9 on 2026-08-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_worklocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklocation',
            name='address',
        ),
        migrations.AddField(
            model_name='worklocation',
            name='building_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='google_map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='street',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='unit_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
