# Generated by Django 5.2.9 on 2026-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_leave_and_work_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100, verbose_name='اسم الشفت')),
                ('shift_order', models.PositiveIntegerField(verbose_name='رقم الشفت')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='وقت بداية الاستراحة')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='وقت نهاية الاستراحة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
        ),
    ]
