# Generated by Django 5.2.9 on 2026-08-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0006_payrollrun_payroll_payroll_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationScoreAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evaluation_scores/', verbose_name='Attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluation Score Attachment',
                'verbose_name_plural': 'Evaluation Score Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='hr_uniq_department_name_per_company',
        ),
        migrations.RemoveField(
            model_name='evaluationscore',
            name='attachment',
        ),
        migrations.AddField(
            model_name='evaluationscoreattachment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_score_attachments', to='accounts.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='evaluationscoreattachment',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr.evaluationscore', verbose_name='Evaluation Score'),
        ),
    ]
