# Generated by Django 5.2.9 on 2026-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_worklocation_address_worklocation_building_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpermission',
            name='worklocations_add',
            field=models.BooleanField(default=True, verbose_name='Add Work Location'),
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='worklocations_delete',
            field=models.BooleanField(default=True, verbose_name='Delete Work Location'),
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='worklocations_edit',
            field=models.BooleanField(default=True, verbose_name='Edit Work Location'),
        ),
        migrations.AddField(
            model_name='hrpermission',
            name='worklocations_view',
            field=models.BooleanField(default=True, verbose_name='View Work Locations'),
        ),
    ]
