# Generated by Django 5.2.9 on 2026-01-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['shift_order']},
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.shift')),
            ],
            options={
                'ordering': ['date', 'employee', 'shift'],
                'unique_together': {('employee', 'shift', 'date')},
            },
        ),
    ]
