# Generated by Django 5.2.9 on 2026-08-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_worklocation_google_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='allowed_radius',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Allowed radius in meters'),
        ),
    ]
