# Generated by Django 5.2.9 on 2026-01-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_employeeschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={'ordering': ['date', 'employee']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
