# Generated by Django 5.2.9 on 2026-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_worklocation_allowed_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=1500),
        ),
    ]
