# Generated by Django 5.2.9 on 2026-01-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='الدقائق المتأخرة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.shift', verbose_name='المناوبة'),
        ),
    ]
