# Generated by Django 5.2.9 on 2026-01-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_leave_created_at_leave_leave_type_leave_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='annual_leave_entitlement',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='compensatory_leave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_annual_leave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='national_id_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='other_files',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
