# Generated by Django 5.2.9 on 2026-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('compensatory', 'إجازة تعويضية'), ('other', 'أخرى')], max_length=50),
        ),
    ]
