# Generated by Django 5.2.9 on 2026-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_entitlement',
            field=models.IntegerField(default=0, verbose_name='الإجازة السنوية المستحقة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='compensatory_leave',
            field=models.IntegerField(default=0, verbose_name='الإجازات التعويضية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_annual_leave',
            field=models.IntegerField(default=0, verbose_name='الإجازة السنوية الحالية'),
        ),
    ]
