# Generated by Django 5.2.9 on 2026-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_employee_annual_leave_entitlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='ملف العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='ملف الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='ملفات أخرى'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/', verbose_name='ملف الجواز'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='صورة الموظف'),
        ),
    ]
