# Generated by Django 5.2.9 on 2026-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_employee_contract_file_employee_national_id_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية'),
        ),
    ]
