# Generated by Django 5.2.9 on 2026-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_employee_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجواز'),
        ),
    ]
