BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXX X
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXXXXXXXXX
X
XXXXXXXXXX X
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXX
X
XXXXXX XXX XXXXXX XX X
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXXXX X
    XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X
XXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X
XXXXXXXXXX X
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X
XXXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
BBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Credit Note (Sales Return)') XXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Customer Name') XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Invoice Date') XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Invoice No') XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Return Reason')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X  gettext(u'Cannot return a quantity greater than available') 
    XXXXXX

    XXXX XXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Items') XXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Item') XXXXX
                XXXX gettext(u'Available Quantity') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total After Tax') XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Return Quantity') XXXXX
            XXXXX
        XXXXXXXX

        XXXXXXX
        BBB BBBB BB BBBBB
        XXXX
            XXXXXXXXX
            XXXXFFFFFFFFFFXXXXX
            XXXXFFFFFFFFFFXXXXX
            XXXXFFFFFFFFFFXXXXX
            XXXXFFFFFFFFFFXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX
                XXXXXX XXXXXXXXXXXXX
                       XXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                       XXXXXXX
                       XXXXXXXXXXX
                       XXXXXXXXX
                       XXXXXXXXXXFFFFFFFFFFX
                       XXXXXXXXXXXXFFFFFFFFFFX
                       XXXXXXXXXXXXXXXFFFFFFFFFFX
                       XXXXXXXXXXFFFFFFFFFFXX
            XXXXX
        XXXXX
        BBBBBB
        XXXXXXXX
    XXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Totals') XXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
        XXXXXXXX gettext(u'Total Before Tax:') XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Total After Discount:') XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Tax Value:') XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX gettext(u'Total After Tax:') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    XXXXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Save Return') XXXXXXXXX
    XXXXXX

XXXXXX
XXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXX
    XXXXX X X XXXXXXXXXXXXXX
    XXXXXX XXXXXXXX X X X XX
X

XXXXXXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXX X XX
    XXX XXXXXXXXXXXXXXXXXXXX X XX
    XXX XXXXXXXXX X XX

    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXX X XXXXXXXXXXXXXXXXXXX

        XX XXXX X XXXXXX X XXXXXXXXXX
            XXX X XXXXXXX
            XXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        X

        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXX X XXXXX X XXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXX X XXX X XXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXX XX XXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXX XX XXX X XXXXXXXXXXXXXX
        XXXXXXXXX XX XXX X XXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXX

XXXXXXXXXXXXX
XXXXXXXXX

BBBBBBBB