BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
XX XXX XXXXX XXXX XX XXXXX XX
XXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
    XXXXXXX XXXX X XXXX XX
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X
XXXXXX XXXXX X
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
X
XXXXXXXXXXXX X XXXXXX XXXXXXXX X
XXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
XXXXXXXXXXXX X XXXXXX XXXXXXXX X
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXX XXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
X
XXXXXXXXXXXXXXX XXX
XXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXX XXX XXXXX XXXXX
    XXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXX
X
XXXXXXXX

XXXX X XXXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        X  gettext(u'Print') 
    XXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        X  gettext(u'Download PDF') 
    XXXX

    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        X  gettext(u'Invoice Return') 
    XXXX

    BB BBBBBBBBBBBBBBB B B
    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
        X  gettext(u'Pay') 
    XXXX
    BBBBB

XXXXXX

XXXX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB B BBB BBBBBBBBBBBBBBBBBBBBBBB B B
        XXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Unpaid') XXXXXXX
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB B B BBB BBBBBBBBBBBBBBB B B
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Partially Paid') XXXXXXX
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB B B BBB BBBBBBBBBBBBBBB BB B
        XXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Fully Paid') XXXXXXX
    BBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sales Invoice') XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXX gettext(u'Invoice No:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Customer:') XXXXXXXXX XXXX

            BB BBBBBBBBBBBBBBBBBBB
            XXXXXXXXXXX gettext(u'Description:') XXXXXXXXX XXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Invoice Date:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Issue Date:') XXXXXXXXX XXXX
        XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Item') XXXXX
                XXXX gettext(u'Description') XXXXX
                XXXX gettext(u'Quantity') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXX gettext(u'Total Before Tax:') XXXXXXXXX XXXXXX
        XXXXXXXXXXXXX gettext(u'Total After Discount:') XXXXXXXXX XXXXXX
        XXXXXXXXXXXXX gettext(u'Total Tax:') XXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Total After Tax:')  
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Remaining Balance:')  
        XXXXXX

    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX X XXXXXXX X XXXXXXXXX
        X  gettext(u'Receipts / Payments') 
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
                XXXX
                    XXXX gettext(u'Voucher No') XXXXX
                    XXXX gettext(u'Date') XXXXX
                    XXXX gettext(u'Amount') XXXXX
                    XXXX gettext(u'User') XXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX
        BBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
             gettext(u'No payments linked to this invoice') 
        XXXX
        BBBBB
    XXXXXX
XXXXXX

XXXX XXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX gettext(u'Pay Invoice No')  XXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
            BBBBBBBBBB

            XXXXXX XXXXXXXXXXXXXXXX gettext(u'Amount') XXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                   XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX

            XXXXXX XXXXXXXXXXXXXXXX gettext(u'Account (Cash / Bank)') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                BBB B BB BBBBBBBBBBBBB
                    XXXXXXX XXXXXXXXX X XXXXXXXXX
                BBBBBB
            XXXXXXXXX

            XXXXXX XXXXXXXXXXXXXXXX gettext(u'Description') XXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
                   XXXXXXX gettext(u'Payment for Invoice')  XX

            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Save Payment') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Cancel') 
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
X
XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
X
XXXXXXXXX

BBBBBBBB