BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Invoice List') BBBBBBBB

BBBBB BBBB
XXXXXXX
    XXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXX
    X

    XXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXX XXX XXXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXX XX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
    X

    XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X

    XXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Showing invoices from')    gettext(u'to')  
XXXXXX
BBBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXXX gettext(u'Invoice List') XXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXX XXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X  gettext(u'Add Invoice') 
    XXXX
XXXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
        XXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search ID') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Invoice No') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Customer') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Date') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Total') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Status') XXXXXXX
            XXXXXXXXX
        XXXXX

        XXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX
            XXXX gettext(u'Invoice No') XXXXX
            XXXX gettext(u'Customer') XXXXX
            XXXX gettext(u'Date') XXXXX
            XXXX gettext(u'Total') XXXXX
            XXXX gettext(u'Status') XXXXX
            XXXX gettext(u'Actions') XXXXX
        XXXXX
    XXXXXXXX

    XXXXXXX
    BBB BBBBBBB BB BBBBBBBB
        XXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXX
                BB BBBBBBBBBBBBBBBBBBBBBBB
                    
                BBBB
                     gettext(u'Cash') 
                BBBBB
            XXXXX
            XXXXFFFFFFFFFFF FFFFXXXXX
            XXXXXXXXX
            XXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBB BB B
                         gettext(u'Unpaid') 
                    BBBB
                         gettext(u'Paid') 
                    BBBBB
                XXXXXXX
            XXXXX
            XXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Options') 
                    XXXXXXXXX

                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX

                        BB BBBBBBBBBBBB BB BBBBBBB
                            XXXX
                                XX XXXXXXXXXXXXXXXXXXXXX
                                   XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'View') 
                                XXXX
                            XXXXX

                            XXXX
                                XX XXXXXXXXXXXXXXXXXXXXX
                                   XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX  gettext(u'Download PDF') 
                                XXXX
                            XXXXX

                            XXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                   XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Invoice Return') 
                                XXXX
                            XXXXX
                        BBBB
                            XXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                     gettext(u'View from POS only') 
                                XXXXXXX
                            XXXXX
                        BBBBB

                    XXXXX
                XXXXXX
            XXXXX
        XXXXX
    BBBBB
        XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'No invoices found') XXXXX
        XXXXX
    BBBBBB
    XXXXXXXX
XXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
                X
            XXX
        XXX
    XXX
XXX
XXXXXXXXX

BBBBBBBB