BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sales Invoice') XXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXX gettext(u'Invoice No:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Customer:') XXXXXXXXX XXXX

            XXXX X XXXX XXXXXXXXXXX XXX
            BB BBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXX gettext(u'Description:') XXXXXXXXX XXXX
            BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Invoice Date:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Issue Date:') XXXXXXXXX XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXX XXXXX XXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Item') XXXXX
                XXXX gettext(u'Description') XXXXX
                XXXX gettext(u'Quantity') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total') XXXXX
            XXXXX
        XXXXXXXX

        XXXXXXX

            BBB BBBB BB BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB

            XXXX XXXXX XXXX XX XXXXXX XXXXX XX XXX
            BBB B BB BBBBBBBBBBBB
                BB BBBBBBBBBBBBBBB B BBBBBBBBBBBB
                XXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
                BBBBB
            BBBBBB

        XXXXXXXX
    XXXXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX XXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX X XX XXXX XXX
    XXXX XXXXXXXXXXXXX X XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX X XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total Before Tax:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total After Discount:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    
                BBBB
                    
                BBBBB
            XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total Tax:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total After Tax:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                
            XXXXXXX
        XXXXXX

    XXXXXX
XXXXXX

BBBBBBBB