BBBB BBBBBB
BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBX
      XXXXXBB BBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBBBBBBBBBXXXXXXXX

XXXXXXX
    XXXX X
        XXXXXXXXX
        XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
    X

    XX XX XXXX XX
    XXXXXXXX X
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXX XXXXXX
    X

    XXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
    X

    XXXXX XXXXX XX X
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X

    XXXXX XXXXX XX X
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXX
    X
XXXXXXXX

XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXX
        BBBBB BBBBBBB
        BBBBBBBB
XXXXXX

XXXXXXX
XXXXXXX