BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
    XXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXX XXXXX
    X
    XXX XX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXX
    X
    XXXXXX X
        XXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXX
    X
    XXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
    X
XXXXXXXX

XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sales Invoice') XXXXX

XXXX XXXXXXX XXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXX gettext(u'Invoice No:') XXXXXXX XXXX
    XXXXXXXX XXXXXXXXXXXXXX gettext(u'Customer:') XXXXXXX XXXX

    BB BBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXX gettext(u'Description:') XXXXXXX XXXX
    BBBBB

    XXXXXXXX XXXXXXXXXXXXXX gettext(u'Invoice Date:') XXXXXXX XXXX
    XXXXXXXX XXXXXXXXXXXXXX gettext(u'Issue Date:') XXXXXXX XXXX
XXXXXX

XXXX XXXXX XXXXX XXX
XXXXXXX
    XXXXXXX
        XXXX
            XXXX gettext(u'Item') XXXXX
            XXXX gettext(u'Description') XXXXX
            XXXX gettext(u'Quantity') XXXXX
            XXXX gettext(u'Price') XXXXX
            XXXX gettext(u'Discount') XXXXX
            XXXX gettext(u'Tax %%') XXXXX
            XXXX gettext(u'Total') XXXXX
        XXXXX
    XXXXXXXX

    XXXXXXX
        BBB BBBB BB BBBBB
        XXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXXX
            XXXXXXXXX
        XXXXX
        BBBBBB

        XXXX XXXXX XXXX XXXXXX X XXXX XXX XXXXX XXXXXX XXX
        BBB B BB BBBBBBBBBBB
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBBBB
    XXXXXXXX
XXXXXXXX

XXXXX

XXXX XXXXXX X XX XXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX

        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

            XXXXXXXX XXXXXXXXXXXXXX gettext(u'Total Before Tax:') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX

            XXXXXXXX XXXXXXXXXXXXXX gettext(u'Total After Discount:') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        
                    BBBB
                        
                    BBBBB
                XXXXXXX
            XXXX

            XXXXXXXX XXXXXXXXXXXXXX gettext(u'Total Tax:') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX

            XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Total After Tax:') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                XXXXXXX
            XXXX

        XXXXX
    XXXXX
XXXXXXXX

BBBBBBBB