BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXX XXXXX
        XXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXXX
        XXXXXX XX
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX X X XXX XXXX
        XXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXX XXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
    X

    XXXXXXXXX X
        XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X

    XXXXXXXXXXXXXX
        XXXXXXX XXXXX
        XXXXXXXX X XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXX
        XXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
    X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXX XXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX X X XXX XXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

XXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Create Invoice') XXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
BBBBBBBBBB
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXX XXXXXXXXXXX XXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Invoice No:') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Invoice Date:') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Issue Date:') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Customer:') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX gettext(u'Search customer...') X XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX
    X  gettext(u'Add Customer') 
XXXXXXXXX
XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXX
    XXXXXXX gettext(u'Description:') XXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXX XXXX XXXXXX
XXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX
    X  gettext(u'Add Product') 
XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX
    XXXX gettext(u'Item') XXXXX
    XXXX gettext(u'Description') XXXXX
    XXXX gettext(u'Quantity') XXXXX
    XXXX gettext(u'Price') XXXXX
    XXXX gettext(u'Discount') XXXXX
    XXXX gettext(u'Tax %%') XXXXX
    XXXX gettext(u'Total') XXXXX
    XXXX gettext(u'Cost Center') XXXXX
    XXXX gettext(u'Delete') XXXXX
XXXXX
XXXXXXXX

XXXXXX XXXXXXXXXXXXXXXXX

XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX

XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Search product...') X XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXX

XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Example: 10 or 10%%') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX

XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'Select Cost Center') XXXXXXXXX
        BBB BB BB BBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
    XXXXXXXXX
XXXXX

XXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Delete') 
    XXXXXXXXX
XXXXX

XXXXX

XXXXXXXX
XXXXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXX
XXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
    X  gettext(u'Add Row') 
XXXXXXXXX
XXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Before Tax:') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total After Discount:') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Tax:') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total After Tax:') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXX
         gettext(u'Save Invoice') 
    XXXXXXXXX
XXXXXX

XXXXXXX
XXXXXX
BBBBBBBB