BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
         gettext(u'Create Credit Note (Sales Return)') 
    XXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Customer:') XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXX gettext(u'-- Select Customer --') XXXXXXXXX
        BBB B BB BBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
    XXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Sales Invoice:') XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'-- Select customer first --') XXXXXXXXX
    XXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
           XXXXXXXXXXXXXX
             gettext(u'Continue Creating Return') 
        XXXX
    XXXXXX

XXXXXX

XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXX XXXXXXXX X XXXX XXXXX XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

    XXXXX XXXXXXXXXX    X XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX gettext(u'Loading...') XXXXXXXXXXX

    XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX gettext(u'-- Select customer first --') XXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XX XXXXXXXXXXX
        XXXXXXXXXX XX X

            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXX gettext(u'-- Select invoice --') XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                         gettext(u'Invoice No.')  XXXXXXXXXXXXXXXXX
                        X XXXXXXXXXXXX  gettext(u'SAR') 
                        X XXXXXXXXXXX
                    XXXXXXXXX
                XX
            XXX
        XXX
XXX


XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXX XXXXXXX X XXXXXX XXXXXXXX XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

    XXXXX XXXXXXXXX X XXXXXXXXXXX
    XXXXX XXX       X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX X XXXX XXXXX XX XXXXXXXXX
    XXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBB BXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX

BBBBBBBB