BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXX gettext(u'Invoice Returns') XXXXX
    XXXXXX

XXXX XX XXXX XXXXX XX XXX
BB BBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX

    XXXXXXX

        XXXX X XXXXXX XXX X XXX
        XXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search No.') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Original Invoice') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Return') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Customer') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Date') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Total') XXXXXXX
            XXXXXXXXX
        XXXXX

        XXXX X XXXXXX XXX X XXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX
            XXXX gettext(u'Original Invoice No.') XXXXX
            XXXX gettext(u'Return Invoice No.') XXXXX
            XXXX gettext(u'Customer') XXXXX
            XXXX gettext(u'Return Date') XXXXX
            XXXX gettext(u'Total') XXXXX
            XXXX gettext(u'Actions') XXXXX
        XXXXX

    XXXXXXXX

    XXXXXXX

        BBB B BB BBBBBBB
        XXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX

XXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Options') 
        XXXXXXXXX

XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXX
XX XXXXXXXXXXXXXXXXXXXXX
   XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
     gettext(u'Create Return') 
XXXX
XXXXX

    XXXX
        XX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'View Original Invoice') 
        XXXX
    XXXXX

    XXXX
        XX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Download PDF') 
        XXXX
    XXXXX

XXXXX
    XXXXXX
XXXXX

        XXXXX
        BBBBBB

    XXXXXXXX

XXXXXXXX

BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'No returns yet.') 
XXXXXX
BBBBB

XXXXXX

XXXX XX XXXXXX XXXXXX X XXXXXX XX XXX
XXXXXXX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
X
XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXX XXX XXXXX
X
XXXXXXXX

XXXX XX XXXXXX XXXXXX XX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X

    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXX XX X

                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
                X

            XXX

        XXX

    XXX

XXX
XXXXXXXXX

BBBBBBBB