BBBB BBBB

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
         gettext(u'Create Debit Note (Return)') 
    XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Supplier:') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select Supplier --') XXXXXXXXX
            BBB B BB BBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Invoice:') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select Invoice --') XXXXXXXXX
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXX gettext(u'Invoice Number:') XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXX gettext(u'Invoice Date:') XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXX gettext(u'Product') XXXXX
                    XXXX gettext(u'Quantity') XXXXX
                    XXXX gettext(u'Price') XXXXX
                    XXXX gettext(u'Tax %%') XXXXX
                    XXXX gettext(u'Discount') XXXXX
                    XXXX gettext(u'Total') XXXXX
                XXXXX
            XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX

        XXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXX
             gettext(u'Continue Creating Return') 
        XXXXXXXXX
    XXXXXX

XXXXXX

XXXXXXXX
XXX XXXXXXXXXXXXXXXXX X XXX

XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXX      X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XXXXXXXXXX X XXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXX gettext(u'-- Select Invoice --') XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXX

    XX XXXXXXXXXXXXX XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XX XXXXXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                         gettext(u'Invoice No') SSSSSSS SS XXXXXXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXX
                    XXXXXXXXX
                XXX
            XXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
        XXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXX

    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXX
        XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XX XXXXXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXX X XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                XXX
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXXX
        XXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX