BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
    X

    XX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XX
    XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXX
        XXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
    X

    XX XXXXX XXXXXXX XXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
XXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Create Purchase Invoice') XXXXX

XXXXX XXXXXXXXXXXXXX
BBBBBBBBBB
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXX XXXXXXXXXXX XXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Invoice Number') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Invoice Date') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Issue Date') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Delivery Date') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Supplier') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX gettext(u'Search for a supplier.') X XXXXXXXXXXXXXXXXXXX

            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX
            X  gettext(u'Add Supplier') 
        XXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXX
    XXXXXXX gettext(u'Description') XXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
            X  gettext(u'Add Product') 
        XXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX
    XXXX gettext(u'Product') XXXXX
    XXXX gettext(u'Description') XXXXX
    XXXX gettext(u'Quantity') XXXXX
    XXXX gettext(u'Price') XXXXX
    XXXX gettext(u'Discount') XXXXX
    XXXX gettext(u'Tax %%') XXXXX
    XXXX gettext(u'Total') XXXXX
    XXXX gettext(u'Cost Center') XXXXX
    XXXX gettext(u'Delete') XXXXX
XXXXX
XXXXXXXX

XXXXXX XXXXXXXXXXXXXXXXX
XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                   XXXXXXXXXXXXX gettext(u'Search for a product.') X XXXXXXXXXXXXXXXXXXX

            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXX
    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Example: 10 or 10%%') XX
    XXXXX

    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'Select Cost Center') XXXXXXXXX
            BBB BB BB BBBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXX
    XXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
    XXXXX
XXXXX
XXXXXXXX
XXXXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
        X  gettext(u'Add Row') 
    XXXXXXXXX
XXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXX XXX XXXXXX
XXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Total Before Tax') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Total Discount') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Total Tax') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Total After Tax') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
         gettext(u'Save Invoice') 
    XXXXXXXXX
XXXXXX

XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

    XXXXX XXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Select Cost Center') XX
    XXXXX XXXXXXXXXXXXXXXXXXXXX X X gettext(u'No results found') XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Failed to load data') XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Search for a product.') XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Search for a supplier.') XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Example: 10 or 10%%') XX
    XXXXX XXXXXXXXXXX X X gettext(u'Delete') XX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX

    XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XX XXXXXXX XXXX XX
    XXXXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXX
    XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXX
    XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXX

    XX XXXXXXX XXXX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXX X XXXXX X XXXXXX
        XXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXXX
    XXX

    XX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXX XXXXXXXXX
        XXXXX X X XXXXXXXXXXXXXX
        XXXXXX XXXXXXXX X X X XX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX X X XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX

        XX XXXX XXXXXX XX

        XX XXXXXXXXXXXXXXXXX X
            XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX X XXXX X XXXXXX
        X

        XXXXXX XXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXX X XXX X XXXXXX

        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

        XXXXX XXXXXXXXX X XXXX X XXXXXXXXX
        XXXXX XXX X XXXXXXXXXX X XXXXXXXX X XXXXXX
        XXXXX XXXXXXXX X XXXXXXXXX X XXXX

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX

        XXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXX X XX XXXXXXX X XX XXXXXX X XX XXXXXXXX X XX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX X X XXXXXXXXXXXXX
            XXXXXXXXX XX XXXXXXXXXXXX
            XXXXXXX XX XXXXXXXXXXX
            XXXXXX XX XXXXXX
            XXXXXXXX XX XXXXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXX
        XXX
    X

    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXXXX X

        XXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXX
        X

        XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXX X XXX
            XXXXXXXXXXXXXXXXXX X XXXXXXXX

            XX XXXXXX XX XXXXXXXXXXXXX X
                XXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXXX XX X
                XXXXX XXXXX X XXXXXXXXXXXXXX
                XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXX XX XXXX
                XXXXXXXXX X XX XX X
                    XXXXXXXXXXX X XXXXXX
                    XXXXXXXXXXXX X XXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                    XX XXXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XX
                XXXXXXXXXXXXXXXXXXXX
            XXX
        X

        XXXXXXXX XXXXXXXX
            XXXXXXXXX X XXXXX X XXXXXXXXXXXXXXXXXXXX XX XXXX
                XXXXXXX XX XXXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXX XX X
                    XXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        XXX
    X

    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXX   X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXX XX XXXXX XX XXXXXXX XX XXXXXXXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                XXXXXXX XX XXXXXXXXX
                XXXXXXXXX XX X
                    XXXXXXXXXXXXXXXX X XXXXXXXXXX
                    XXXXXXXXXX
                XX
                XXXXXXXXX XX XXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXX
        XXX XXXX X XXXXXXX X XX

        XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX X XXXXXX X XXXXX
        XXXXXXXXXXXX X XXXXXXXXXXX

        XXXXXXXXXXXX X X
            XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BB BB BBBBBBBBBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXX
            XXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        XX

        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXX X XXXXX X XXXXXX
            XXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXX
        XXX

        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX
    XXX

    XX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXX

        XXXXXXXXX XXX XXXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXX
    XXX

    XXXXXXXXXX

XXX
XXXXXXXXX

BBBBBBBB