BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Purchase Invoices List') BBBBBBBB

BBBBB BBBB
XXXXXXX
    XXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXX
    X

    XXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXX XXX XXXXX
    X

    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXX XX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
    X

    XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X

    XXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Purchase Invoices List') XXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXX
        X  gettext(u'Add Purchase Invoice') 
    XXXX
XXXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXX

        XXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search ID') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Invoice No') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Supplier') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Date') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Total') XXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Status') XXXXXXX
            XXXXXXXXX
        XXXXX

        XXX XXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'No.') XXXXX
            XXXX gettext(u'Invoice No') XXXXX
            XXXX gettext(u'Supplier') XXXXX
            XXXX gettext(u'Date') XXXXX
            XXXX gettext(u'Total') XXXXX
            XXXX gettext(u'Status') XXXXX
            XXXX gettext(u'Actions') XXXXX
        XXXXX

    XXXXXXXX

    XXXXXXX
    BBB BBBBBBB BB BBBBBBBB
        XXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX

            XXXX
                FFFFFFFFFFFFF
            XXXXX

            XXXX
                BB BBBBBBBBBBBBBBBBBBBBBBB B B
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Paid') 
                    XXXXXXX
                BBBB
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Unpaid') 
                    XXXXXXX
                BBBBB
            XXXXX

            XXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Options') 
                    XXXXXXXXX

                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
XXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
        XX  gettext(u'View') 
    XXXX
XXXXX

XXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
        X  gettext(u'Download PDF') 
    XXXX
XXXXX

XXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXX
        XX  gettext(u'Print') 
    XXXX
XXXXX

XXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
        X  gettext(u'Create Debit Note') 
    XXXX
XXXXX
                    XXXXX
                XXXXXX
            XXXXX
        XXXXX
    BBBBB
        XXXX
            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'No purchase invoices found') XXXXX
        XXXXX
    BBBBBB
    XXXXXXXX
XXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
                X
            XXX
        XXX
    XXX
XXX
XXXXXXXXX

BBBBBBBB