BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
    XXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXX XXXXX
    X
    XXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXXX
        XXXXXX XX
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX X X XXX XXXX
        XXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXX X
        XXXXXXXX XXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXX
        BB BBBBBBBBB
             gettext(u'Edit Purchase Order No %(po.po_no)s') SSSS SSSSSSSS SSSSS SS SSSSSSSSSSSS
        BBBB
             gettext(u'Create Purchase Order') 
        BBBBB
    XXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBBBBB

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX

    XXXX XXXXXXXXXXX XXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXX XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Purchase Order No:') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                       XXXXXXXBB BBBBBBBBBBBBBBBBBBXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Issue Date:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXBB BBBBBBBBBFFFFFFFFFFFFBBBBBXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Delivery Date:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXBB BBBBBBBBBFFFFFFFFFFFFBBBBBXX
            XXXXXX

        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Supplier:') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                           XXXXXXXXXXXXX gettext(u'Search for a supplier...') X XXXXXXXXXXXXXXXXXXX

                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                    X  gettext(u'Add Supplier') 
                XXXXXXXXX
            XXXXXX

        XXXXXX

        XXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXXXXX gettext(u'Description:') XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXX

        XXXX XXX XXXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Product') 
            XXXXXXXXX
        XXXXXX

        XXXX XXXXX XXXXX XXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXX gettext(u'Product') XXXXX
                    XXXX gettext(u'Description') XXXXX
                    XXXX gettext(u'Quantity') XXXXX
                    XXXX gettext(u'Price') XXXXX
                    XXXX gettext(u'Discount') XXXXX
                    XXXX gettext(u'Tax %%') XXXXX
                    XXXX gettext(u'Total') XXXXX
                    XXXX gettext(u'Delete') XXXXX
                XXXXX
            XXXXXXXX

            XXXXXX XXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX

                XXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                               XXXXXXXXXXXXX gettext(u'Search for a product...') X XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXX

                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                           XXXXXXXXXXXXXXXXXXX XXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                           XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXX XXXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                           XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX

                XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXXXXXXX

            XXXXX

            XXXXXXXX
        XXXXXXXX

        XXXX XXX XXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Row') 
            XXXXXXXXX
        XXXXXX

    XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Before Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Discount:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Final Total:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXX XXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX
         gettext(u'Save Purchase Order') 
    XXXXXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX

XXXXXXX
XXXXXX

XXXXXXXX
XXXXX XXXXXXXXXXXXXXX X X gettext(u'No results found') XX
XXXXX XXXXXXXXXXXXXXXXXXX X X gettext(u'Search for a product...') XX
XXXXX XXXXXXXXXXXXXXXXXXXXX X X gettext(u'SAR') XX
XXXXX XXXXXXXXXXXXXXXXXXXX X X gettext(u'Search for a supplier...') XX
XXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XX XXXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXX X XXX
            XXXXXXXXXXXXXXXXXX X XXXXXXXX

            XX XXXXXXXXXXXXXX X
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXX XX X
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXXXX

                XXXXXXXXXXX X XX XX X
                    XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXX
                XX

                XXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
X
XXXXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XX XXXXXXXXX
        XXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

    XX XXXXXXXXXXXXXX X
        XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXXXXXXXX XX X
        XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXX X XX XX X
            XXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XX

        XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
X

XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

XXXXXXXX
XXX XXXXXXXX X XX

XXXXXXXX XXXXXXXX X
    XXXXXXXXXXX

    XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX X XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXX

    XXXXXXXXXXXX X X
        XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXX

        XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX

        XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXXXXXXX
    XX

    XXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
X
XXXXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX

    XXXXX XXXXXXXX X XXX X XXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXX X XXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXX X XXXX X XXXXX
    XXXXX XXXXX X XXXXXXXXXXXXX X XXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXX X XX
    XXX XXXXXXXXXXXXX X XX
    XXX XXXXXXXX X XX
    XXX XXXXXXXXXX X XX

    XXXXXXXXXXXXXXX XX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX

        XXXXX XXXXXXXX X XXX X XXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXX X XXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXX X XXXX X XXXXX
        XXXXX XXXXX X XXXXXXXXXXXXX X XXXXXXXXX

        XXXXXXXXXXX XX XXXXXXXXX
        XXXXXXXXXXXXX XX XXXXXXXXX
        XXXXXXXX XX XXXXXXXXX
        XXXXXXXXXX XX XXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXX XXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
X
XXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX X XXXXXXX
        X
    XXX
XXX
XXXXXXXXX

XXXXXXXX
BB BBB BBBBBBBBB
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBB
XXXXXXXXX

BBBBBBBB