BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXXX XXXXXX XXXXXXXX XXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXX gettext(u'Purchase Orders Management') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Create Purchase Order') XXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX

        XXXXXXX

            XXXX XXXXXX XXX XXX
            XXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Purchase Order No') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Supplier') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Date') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Total') XXXXXXX
                XXXXXXXXX
            XXXXX

            XXXX XXXXX XXXXXXX XXX
            XXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX
                XXXX gettext(u'Purchase Order No') XXXXX
                XXXX gettext(u'Supplier') XXXXX
                XXXX gettext(u'Date') XXXXX
                XXXX gettext(u'Total') XXXXX
                XXXX gettext(u'Actions') XXXXX
            XXXXX

        XXXXXXXX

        XXXXXXX

            BBB B BB BBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFFFFXXXXX

                XXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Options') 
                        XXXXXXXXX

                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'View') XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Print') XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXX

            XXXXX
            BBBBB
            XXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'No purchase orders found') XXXXX
            XXXXX
            BBBBBB

        XXXXXXXX

    XXXXXXXX

XXXXXX

XXXXXXX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
X
XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X
XXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X

    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
                X
            XXX

        XXX

    XXX

XXX
XXXXXXXXX

BBBBBBBB