BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Purchase Order') XXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Purchase Order No:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Supplier:') XXXXXXXXX XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXX gettext(u'Delivery Date:') XXXXXXXXX FFFFFFF F FFXXXX
        XXXXXX

    XXXXXX

    XXXX XXXXX XXXXX XXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX
                XXXXXXXXXX
                XXXX gettext(u'Product') XXXXX
                XXXX gettext(u'Description') XXXXX
                XXXX gettext(u'Quantity') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total') XXXXX
            XXXXX
        XXXXXXXX

        XXXXXXX
            BBB BBBB BB BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFFXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBB
            XXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'No items found') XXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX gettext(u'Total Before Tax:') XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX gettext(u'Total After Discount:') XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX gettext(u'Total Tax:') XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX gettext(u'Final Total:') XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

        XXXXXX
    XXXXXX

    XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Edit') XXXX
        XX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Print') XXXX
        XX XXXXXXBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXX gettext(u'Back to List') XXXX
    XXXXXX

XXXXXX

BBBBBBBB