BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
         gettext(u'Create Debit Note (Return)') 
    XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Supplier:') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select Supplier --') XXXXXXXXX
            BBB BBBBBBBB BB BBBBBBBBB
                XXXXXXX XXXXXXXXX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Invoice:') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select Invoice --') XXXXXXXXX
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXX XXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX gettext(u'Invoice Number:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX gettext(u'Invoice Date:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXX gettext(u'Product') XXXXX
                    XXXX gettext(u'Quantity') XXXXX
                    XXXX gettext(u'Price') XXXXX
                    XXXX gettext(u'Tax %%') XXXXX
                    XXXX gettext(u'Discount') XXXXX
                    XXXX gettext(u'Total') XXXXX
                XXXXX
            XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXX
        XXXXXXXX

        XXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Continue Creating Return') 
        XXXXXXXXX

    XXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX X X gettext(u'-- Select Invoice --') XX
XXXXX XXXXXXXXXXXXXXX X X gettext(u'Invoice No') XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Please select an invoice first') XX

XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXX     X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XXXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

    XX XXXXXXXXXXXXX XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XX XXXXXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX X XXXXXXX
                XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXX

    XX XXXXXXXXXXXX XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XX XXXXXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXX X X
                    XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXX

BBBBBBBB