BBBB BBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXX XXXXXBB BBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX

    XXXXXXX

    XXXXXXXXXX X
        XXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    X

    XXXXX XXXXXX XXX XXX XXXXXX XX XXXXX XXX X
        XXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXX
    X

    XXXX X
        XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBX
    X

    XX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX XXXXX
    X

    XXX XX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXX
    X

    XX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXXXBBBBXXXXXXXXBBBBBX
        XXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXX XXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXX XXXX X
        XXXXXXXXXXXX XXXXX
        BB BBBBBBBBBBBBB BB BBBB
        XXXXXXXXXXXXX XXXXX
        BBBB
        XXXXXXXXXXXX XXXXX
        BBBBB
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXX
    X

    XXXXXXXXXXX XXXXX X
        XXXXXX XXXXXX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXX
    X

    XXXXXXX XXX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXX XXXX
    X

    XXXXXXXX
XXXXXXX

XXXXXX

BB BBBBBBB
XXXX XXXXXXXBB BBBBBBBBBBBBB BB BBBBXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXX
XXXXXX
BBBBB

XXXX gettext(u'Purchase Invoice') XXXXX

XXXX XXXXXXXXXXXXXXXXX

    XXXXX
        XXXXXXXXXXX gettext(u'Invoice Number:') XXXXXXXXX XXXX
        XXXXXXXXXXX gettext(u'Supplier:') XXXXXXXXX XXXX

        BB BBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXX gettext(u'Description:') XXXXXXXXX XXXX
        BBBBB
    XXXXXX

    XXXX XXXXXXXBB BBBBBBBBBBBBB BB BBBBXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXBBBBBXX
        XXXXXXXXXXX gettext(u'Invoice Date:') XXXXXXXXX XXXX
        XXXXXXXXXXX gettext(u'Issue Date:') XXXXXXXXX XXXX
    XXXXXX

XXXXXX

XXXXXXX
    XXXXXXX
        XXXX
            XXXX gettext(u'Product') XXXXX
            XXXX gettext(u'Quantity') XXXXX
            XXXX gettext(u'Price') XXXXX
            XXXX gettext(u'Total') XXXXX
        XXXXX
    XXXXXXXX

    XXXXXXX
        BBB BBBB BB BBBBB
        XXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
        XXXXX
        BBBBBB

        BBB B BB BBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBB B BBBBBBBBBBBB
            XXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBB
        BBBBBB
    XXXXXXXX
XXXXXXXX

XXXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXX
        BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX

        XXXXX
            XXXXXX gettext(u'Total Before Tax:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX

        XXXXX
            XXXXXX gettext(u'Total After Discount:') XXXXXXX
            XXXXXX XXXXXXXXXXX
                   XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                   XXXXXXXXX
        XXXXXX

        XXXXX
            XXXXXX gettext(u'Total Tax:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX

        XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Total After Tax:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX

    XXXXXX
XXXXXX

XXXXXXX
XXXXXXX