BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
 gettext(u'Create Debit Note (Purchase Return)') 
BBBBBBBB

BBBBB BBBBBBB

BB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

BBBBBBBB