BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXX XXXXX X
    XXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXX X
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XX  gettext(u'Print Invoice') 
    XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Purchase Invoice') XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXX gettext(u'Invoice Number:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Supplier:') XXXXXXXXX XXXX

            BB BBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXX gettext(u'Description:') XXXXXXXXX XXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Invoice Date:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Issue Date:') XXXXXXXXX XXXX
        XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Product') XXXXX
                XXXX gettext(u'Quantity') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total') XXXXX
            XXXXX
        XXXXXXXX

        XXXXXXX

            BBB BBBB BB BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB

            BBB B BB BBBBBBBBBBBB
                BB BBBBBBBBBBBBBBB B BBBBBBBBBBBB
                XXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
                BBBBB
            BBBBBB

        XXXXXXXX
    XXXXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXX X XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total Before Tax:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total After Discount:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    
                BBBB
                    
                BBBBB
            XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total Tax:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Total After Tax:') XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                
            XXXXXXX
        XXXXXX

    XXXXXX
XXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXX
XXXXXXXXX

BBBBBBBB