BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
         gettext(u'Create Debit Note (Purchase Return)') 
    XXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Supplier:') XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXX gettext(u'-- Select Supplier --') XXXXXXXXX
        BBB B BB BBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
    XXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXXX gettext(u'Select Purchase Invoice:') XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'-- Select supplier first --') XXXXXXXXX
    XXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
           XXXXXXXXXXXXXX
             gettext(u'Continue Creating Return') 
        XXXX
    XXXXXX

XXXXXX

XXXXXXXX
XXXXX XXXXXXXXXXXX X X gettext(u'Loading...') XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'-- Select supplier first --') XX
XXXXX XXXXXXXXXXXXXXXXXXX X X gettext(u'-- Select Invoice --') XX
XXXXX XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'No invoices found for this supplier') XX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Error loading invoices') XX
XXXXX XXXXXXXXXXXXXXX X X gettext(u'Invoice No') XX
XXXXX XXXXXXXX X X gettext(u'SAR') XX

XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXX XXXXXXXX X XXXX XXXXXXXX XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

    XXXXX XXXXXXXXXX    X XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXX XX X
            XX XXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXXXXX
        XX
        XXXXXXXXXX XX X

            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXX

            XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXXXXX XX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        X XXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXX
                XX
            XXX
        XX
        XXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
XXX


XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXX XXXXXXX X XXXXXX XXXXXXXX XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X

    XXXXX XXXXXXXXX X XXXXXXXXXXX
    XXXXX XXX       X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX

BBBBBBBB