BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX
XXXXXXXXX X
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXXXXXXXXX
X

XXXXXXXXXX X
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXX
X

XXXXXX XXX XXXXXX XX X
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XX XXXXX XXXXXXX XX
XXXXXXXXXX X
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X
XXXXXXXX

XXXXX XXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
      XXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBB
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXFFFFFFXX

XXXX XXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
         gettext(u'Debit Note (Purchase Return)') 
    XXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Supplier Name') XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Invoice Date') XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX gettext(u'Invoice Number') XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Return Reason')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X  gettext(u'Cannot return quantity greater than available quantity in the invoice') 
    XXXXXX

    XXXX XXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Items') XXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Product') XXXXX
                XXXX gettext(u'Available Qty') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total After Tax') XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Return Qty') XXXXX
            XXXXX
        XXXXXXXX

XXXXXXX
BBB BBB BB BBBBB
BBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
XXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXFFFFFFFFFXXXXX
    XXXXFFFFFFFFFFXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX
        XXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXX

        XXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXX
               XXXXXXXXX
               XXXXXXX
               XXXXXX
               XXXXXXXXXXX
               XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXFFFFFFFFFX
               XXXXXXXXXXFFFFFFFFFFXX
    XXXXX
XXXXX
BBBBBBB
BBBBBB
XXXXXXXX

    XXXX XXXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Totals') XXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
        XXXX
            XXXX gettext(u'Total Before Tax:') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX
            XXXX gettext(u'Total After Discount:') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX
            XXXX gettext(u'Tax Amount')  XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX gettext(u'Total After Tax:') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    XXXXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            X  gettext(u'Save Return') 
        XXXXXXXXX
    XXXXXX

XXXXXX
XXXXXXX

XXXXXXXX
XXXXX XXXXXXXXXXXXXX X X gettext(u'Cannot return quantity greater than available quantity in the invoice') XX

XXXXXXXX XXXXXXXX X
    XXXXX X X XXXXXXXXXXXXXX
    XXXXXX XXXXXXXX X X X XX
X

XXXXXXXX XXXXXXXXXXXX X

    XXX XXXXXXXXXXXX X XX
    XXX XXXXXXXXXXXXXXXXXXXX X XX
    XXX XXXXXXXXX X XX

    XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXX X XX X X XXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XX X

        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXX
        XXX XXX X XXXXXXXXXXXXXXXXXXX

        XX XXXX X XXXXXXX X
            XXXXXXXXXXX X XXXXXXX
            XXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        X

        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXXXXXXXX X XXXXX X XXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXX X XXX X XXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXX XX XXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXX XX XXX X XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XX XXX X XXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXX

XXXXXXXXXXXXX
XXXXXXXXX

BBBBBBBB