BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Add Leave') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXX gettext(u'Add Leave') XXXXX

    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

            BB BBBBBBBB
                XXXX XXXXXX XXXXX XXXXXXX XXXX XXXXX XXXX XXX
                
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            BBBB
                XXXX XXXXXX XXX XXXXXX XXXX XXXXXXX XXX
                
                BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXX
                BBBBB
            BBBBB
        XXXXXX

        XXXX XXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXX
                BBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Save') 
            XXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Cancel') 
            XXXX
        XXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB