BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Quick Check In and Check Out') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

    XXX XXXXXXXXXXXXX gettext(u'Quick Check In and Check Out') XXXXX

    XXXX XXXXX XXXXX XX XXX XXXX XXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BB BBB BBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Employee is not linked to the user account.') XXXXXX
        BBBB BBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBB
    XXXXXX

    XXXX XXXX XXXXXXX XXXXXX XXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXX XXXXX
                       XXXXXXX XXX XXXXX XXXXXXXX
                       XXXXXXXXXXXXXXXXX XXXXXXXX
                       XXXXXX XXXXX
                       XXXXXXXXXXX XXX XXXXXXX
             _("Check In") 
        XXXXXXXXX
    XXXXXXX

    XXXX XXX XXXXX XXX
    BB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
            XXX gettext(u'Last record:') 
                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                     gettext(u'Checked out at')  FFFFFFFFFF
                BBBB
                     gettext(u'Checked in at')  FFFFFFFFFF
                BBBBB
            XXXX
        XXXXXX
    BBBBB

XXXXXX

XXXXXXX
    XXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXX
    X
    XX X
        XXXXXXXXXXXX XXXXX
        XXXXXX XXXXX
    X
    XXXXXX X
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXX
    X

    XX XXXXX XXXXXX X XXXX XXXX XX
    XXXXX X
        XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXX 
                    X X XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX 
                    X X XXXX XXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXX XXXXXX XX
        XXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
    X
XXXXXXXX

XXXXXXXX
    XX XXX XXXXX XXXXXXX XXX XXXXX
    XXX XXXXXXXXXXXXX X XX
    XXXXX XXXXXXXX X XXXXXX XX XXXXX XXXXX

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXX X XXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXX X XXXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Please wait before making a new record!') XXXXXXXX
                XXXXXX XXXXXX
            X

            XXXXXXXXXXXXX X XXXX
            XX XXXXX XX XXXXX XXXXX
            XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXX X XXX
            X
        XXX
    X
XXXXXXXXX

BBBBBBBB