BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Employee Schedule') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXBB BBBBBBBBBBBBBBB gettext(u'Employee Schedule') BBBBBXXXXX

    XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Month') XXXXXXXX
            XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                BBB B BB BBBBBB
                    XXXXXXX XXXXXXXX BB B BB BBBBBXXXXXXXXBBBBBXXXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Year') XXXXXXXX
            XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                BBB B BB BBBBB
                    XXXXXXX XXXXXXXX BB B BB BBBBXXXXXXXXBBBBBXXXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Employee') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                     gettext(u'All') 
                XXXXXXXXX
                BBB BBB BB BBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX

        XXXX XX XXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                 gettext(u'Save') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Day') XXXXX
                XXXX gettext(u'Date') XXXXX
                BBB BBB BB BBBBBBBBB
                    XXXXXXXXX
                BBBBBB
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBB BB BBBBBBBBBBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                BBB BBBBB BB BBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXXX 
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXFFFFFFFFFFXX
                    XXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                    BB BBBBBBBBBBB
                    XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXX
                BBBBBB
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXX XXXXXX XXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Select Shift') XXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                    
                    BBB BBBBB BB BBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                        
                    XXXXX
                    BBBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBB
XXXXXXX
XXXXXXXXXXX X
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
X
XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
X
XXXXXXXXXXXXXXXX X
    XXXX XXXX
    XXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXX
X
XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXX
X

XXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
X

XXXXX XXX XXXXX XX X
    XXXXXX XXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX
XXX XXXXXXXXXXX X XXXXX
XXXXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX X XXXXXX X
            XXXXXXX gettext(u'Cannot edit past days.') XXX
            XXXXXXX
        X
        XXXXXXXXXXX X XXXXX
        XXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
    XXX
XXX

XXXXXXXX XXXXXXXXXXXXXXX XXXXX X
    XX XXXXXXXXXXXXX X
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX 
    X
    XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXX X XXXXX
    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX XXXXXX XX XXXXXXXX X
            XXXXXX X XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXX
            X
        X
    X
    XXXXXX XXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXX XXXXXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XX
        XXX
    XXX

    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXXXX XX XXXXXXXXXXX
    XXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Error') X XXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
    XXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Unexpected error') XXXXXXXX
    XXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXX
BBBBBBBB