BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Employees') BBBBBBBB

BBBBB BBBBBBB
XXXXXXX
XX XXXXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXX XX
XXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXX XXXXX
X

XX XX XXXXX XXXX XX
XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXX XX XXXXX XX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX XX XXXX XX XXXXXX XX
X

XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
X

XX XXXXXX X XXX XXXX XXXXX XX
XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXX XXXXXX
    XXXXXXX X XXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXXX
    XXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXX
X

XX XXXXXXX XXXXXX XX
XXXXXXXXXXXXXX XX X
    XXXXXXX XXXX X XXX XX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X X
    XXXXXXX XXX XX
    XXXXXXXXXX XXXXXXX
X

XX XXXXXX XX
XXXXXXXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXX XXXX
    XXXXXXXXXXXX XXXXX
X

XX XX XXXXXXX X XXX XXX XX
XXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX XXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXX gettext(u'Employees') XXXXX

    XXXX XX XXXXX XXXX XXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Add Employee') XXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBB BB BBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBB
                    XXXX XXXXXX XXXXX gettext(u'Employee Photo') XX
                BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Employee Photo') XX
                BBBBB
            XXXXXX

            XXXXBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
BB BBBBBBBBBBBBB BB BBBB
     
BBBB
     
BBBBB
XXXXX
            XXX gettext(u'Employee No.') X XXXX
            XXX gettext(u'Department') X BB BBBBBBBBBBBBBBBBBBXXXBBBBBXXXX
            XXX gettext(u'Branch') X BB BBBBBBBBBBBBBBXXXBBBBBXXXX
            XXX gettext(u'Salary') X XXXX
            XXX gettext(u'Hire Date') X XXXX
            XXX gettext(u'Status') X 
                XXXXX XXXXXXXBB BBBBBBBBBBXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXBBBBBXX
                    BB BBBBBBBBBB gettext(u'Active') BBBB gettext(u'Inactive') BBBBB
                XXXXXXX
            XXXX

            XXXX XX XXXXXXX X XXX XXX XXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
        XX XXXXXXXXXXXXXXXXXXXX gettext(u'No employees found') XXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB