BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Payment Voucher') BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX

    XXX XXXXXXXXXXXXXXXXXX XXXXXX
         gettext(u'Payment Voucher') 
    XXXXX

    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXX XXXXX XXX
        XXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Party Type') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select --') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Customer') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Supplier') XXXXXXXXX
        XXXXXXXXX

        XXXX XXXXX XXX
        XXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Party') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select Party Type First --') XXXXXXXXX
        XXXXXXXXX

        XXXX XXXXXX XXXXXX XXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

        XXXX XXXXXX XXX
        XXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Cash / Bank Account') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'-- Select Account --') XXXXXXXXX
            BBB B BB BBBBBBBBBBBBB
                XXXXXXX XXXXXXXXX X XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXX XXXXXX XXX
        XXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Amount') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX

        XXXX XXXXXX XXX
        XXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Description') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                 gettext(u'Save & Post') 
            XXXXXXXXX
        XXXXXX

    XXXXXXX
XXXXXX

XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXX
            XXXXXXXXXXXX X gettext(u'-- Select Party --') XX
            XXXXXXXXXXX XXXX
        XXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
            XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Loading...') XXXXXXXXXXXX

        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'-- Select Party --') XXXXXXXXXXXX

            XX XXXXX XX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX
                XXX
            X

            XXXXXXXXXXXXXX
        XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXX X X XXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXX
                XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXX gettext(u'-- Select Party Type First --') XXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXX XXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX XX XXXXXXXXXX XXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    XXX
XXXXXXXXX

BBBBBBBB