BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'View Receipt Voucher') BBBBBBBB

BBBBB BBBBBBB

XXX XXXXXXXXXXXXX
    X  gettext(u'Receipt Voucher No')  FFFFFFFFFFFFFFFFFF
XXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX

  XXXX
    XXXX gettext(u'Customer') XXXXX
    XXXXXXXXX
  XXXXX

  XXXX
    XXXX gettext(u'Date') XXXXX
    XXXXXXXXX
  XXXXX

  XXXX
    XXXX gettext(u'Amount') XXXXX
    XXXXXXXXX
  XXXXX

  XXXX
    XXXX gettext(u'Status') XXXXX
    XXXXXXXXX
  XXXXX

  XXXX
    XXXX gettext(u'Created By') XXXXX
    XXXXXXXXX
  XXXXX

XXXXXXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
  X  gettext(u'Back') 
XXXX

BBBBBBBB