BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXX XXX
XXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXX XXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXXXX X
        XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
    X

    XXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXX
        XXXX XXXX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXX XXXXX
    X

    XXXXXXXXXXXXX X X
        XXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXX XXXXXXX X
        XXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXX XXXXXXX X
        XXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX
                 gettext(u'Chart of Accounts') 
            XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXX

        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXX XX X

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX X
            XXXXX X
                XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                XXXXX XXXXXXXXXXXXXX X
                    XXXXXX X XXX XXXXXXX XX
                XX
                XXXXXXXXX XXXXXX
            XX
            XXXXXXX X XXXXX XXXXX XXXXXX XXXX XX
            XXXXXXXXXXXXXXX XXXX
        XX
        XXXXXXXX XXXXXXXXXXXXX
        XXXX BB BBBBBBBBBBBBB BB BBBBXXXXBBBBXXXXXBBBBB
    XXX

    XXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX X
            XXXXX XXX X XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX XXXXXXX

            XXXXX XX X XXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXX XXX XXXX

            XXX XXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX XXXXXXX
                   XXXXXXX gettext(u'View') X
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX XXXXXXXX
                   XXXXXXX gettext(u'Add Child') X
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX

            XX XXXXXXXXXX X
                XXXXXXX XX XXX XXXXXXXXX XXXXXXX
                   XXXXXXX gettext(u'Edit') X
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXX XX X
                    XXXXXXX XX XXX XXXXXXXXX XXXXXXXX XXXXXXX
                       XXXXXXX gettext(u'Delete') X
                       XXXXXXXXXXXXXXXXXXXXX gettext(u'Confirm deletion?') XXX X
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXX
                X
            X

            XXXXXXX XX XXXXXXXXXX

            XXXXX XXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXX
    XXX

XXX
XXXXXXXXX

BBBBBBBB