BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

BBBBB BBBBBBB

XXXXXXX
XXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
X
XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X

XXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
XXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X

XXXXXXXXXXXXXXXXXX X XXXXXX XXXX XXXXXXXXXXX X

XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXX gettext(u'Add Manual Journal Entry') XXXXX

        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
             gettext(u'Back') 
        XXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX

                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Date') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Description') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXX gettext(u'Enter description') X
                               XXXXXXXXX
                    XXXXXX

                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXX

                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX

                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXXXXXXXX
                            XXXX gettext(u'Account') XXXXX
                            XXXX gettext(u'Debit') XXXXX
                            XXXX gettext(u'Credit') XXXXX
                        XXXXX
                    XXXXXXXX

                    XXXXXXX

                        BBB B BB BBBBBBBBBBBBBB
                        BB BBBBBBBBBBBBBBB BB B
                        XXXX
                            XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                                    BBB B BB BBBBBBBB
                                        XXXXXXX XXXXXXXXX X XXXXXXXXX
                                    BBBBBB
                                XXXXXXXXX
                            XXXXX
                            XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                       XXXXXXXXXXXXXXXXX
                                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                       XXXXXXXXXXXXXXXXXX
                                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXX
                        BBBBB
                        BBBBBB

                    XXXXXXXX

                    XXXXXXX
                        XXX XXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXX gettext(u'Total') XXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                    XXXXXXXX

                XXXXXXXX

            XXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX

        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Row') 
            XXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                X  gettext(u'Save Entry') 
            XXXXXXXXX

        XXXXXX

    XXXXXXX
XXXXXX

XXXX XXXXXXX XXXX XXXXX XXXX XXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXX XXXXXXXXX X XX

XXXXXXXX XXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXX
        XXXX XBB BBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBX
    XXX
X

XXXXXXXX XXXXXXXX X
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX

    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXX X X
        XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                BBB B BB BBBBBBBB
                    XXXXXXX XXXXXXXXX X XXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXX
        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX

    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXX XXXXX X XX XXXXXX X XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXXXXXXXXXXXXXXXXXX XX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXX XXX X XX XXXXXX XXX XX X
        XXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXX X XXXXX
        XXXXXXX
    X

    XX XXXXXX XXX XXXXXXX X
        XXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Not Balanced') XXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXX
    X XXXX X
        XXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Balanced Entry') XXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXX
    X
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXX
XXX
XXXXXXXXX

BBBBBBBB