BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
XXXXXXX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X
XXXXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Customer List') XXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Add Customer') XXXX
        XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX

            XXXX XXXXXX XXX XXX
            XXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search No.') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Customer') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Invoice Count') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Balance') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Status') XXXXXXX
                XXXXXXXXX
            XXXXX

            XXXX XXXXXXXX XXXXXX XXX XXX
            XXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX
                XXXX gettext(u'Customer') XXXXX
                XXXX gettext(u'Invoice Count') XXXXX
                XXXX gettext(u'Balance') XXXXX
                XXXX gettext(u'Status') XXXXX
                XXXX gettext(u'Actions') XXXXX
            XXXXX

        XXXXXXXX

        XXXXXXX
            BBB B BB BBBBBBBBB
            XXXX
                XXXXXXXXX

                XXXXXXXXX

                XXXXXXXXX

                XXXXXXXXX

                XXXX
                    BB BBBBBBBBB B B
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Debtor') XXXXXXX
                    BBBB BBBBBBBBB B B
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Creditor') XXXXXXX
                    BBBB
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Balanced') XXXXXXX
                    BBBBB
                XXXXX

                XXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                             gettext(u'Options') 
                        XXXXXXXXX

                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'View') XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Edit') XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX

XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
                X
            XXX
        XXX
    XXX
XXX
XXXXXXXXX

BBBBBBBB