# Generated by Django 5.2.9 on 2026-07-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_is_payment_method'),
        ('accounts', '0001_initial'),
        ('pos', '0002_paymentmethod_account_paymentmethod_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_pos_payment_method_company',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.company', verbose_name='الشركة'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_pos_payment_method_per_company'),
        ),
    ]
