# Generated by Django 5.2.9 on 2026-07-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_paymentmethod_unique_pos_payment_method_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
