# Generated by Django 5.2.9 on 2026-07-17 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_invoiceitem_discount_invoiceitem_tax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الفاتورة'),
        ),
    ]
