# Generated by Django 5.2.9 on 2026-01-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.paymentmethod'),
        ),
    ]
