# Generated by Django 5.2.9 on 2026-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Amount')], default='amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
