# Generated by Django 5.2.9 on 2026-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
