BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Quotation') XXXXX

    XXXX XXXXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXX gettext(u'Quotation No:') XXXXXXXXX XXXX
            XXXXXXXXXXX gettext(u'Customer:') XXXXXXXXX XXXX

            XX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX gettext(u'Description:') XXXXXXXXX 
            XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Quotation Date:') XXXXXXXXX XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXX XXXXX XXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXX gettext(u'Item') XXXXX
                XXXX gettext(u'Description') XXXXX
                XXXX gettext(u'Quantity') XXXXX
                XXXX gettext(u'Price') XXXXX
                XXXX gettext(u'Discount') XXXXX
                XXXX gettext(u'Tax %%') XXXXX
                XXXX gettext(u'Total') XXXXX
            XXXXX
        XXXXXXXX

        XXXXXXX

            BBB BBBB BB BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXX
            XXXXX
            BBBBBB

            XXXX XXXXX XXXX XXX
            BBB B BB BBBBBBBBBBBB
                BB BBBBBBBBBBBBBBB B BBBBBBBBBBBB
                XXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                BBBBB
            BBBBBB

        XXXXXXXX
    XXXXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Total Before Tax:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                          XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Total Discount:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                          XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Total After Discount:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                          XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Total Tax:') XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                          XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Total After Tax:') 
            XXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                          XXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX

    XXXXXX
XXXXXX

BBBBBBBB