BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Create Quotation') XXXXX

XXXX XXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX

    XXXX XXXXXXXXXXX XXXXX

        XXXX XXXXXXXXX XX X XXXX XXX
        XXXX XXXXXXXXXX XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Quotation No:') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Quotation Date:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX

        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Customer:') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Customer') XXXXXXXXX
                    BBB B BB BBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXXXXX gettext(u'Description:') XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXX XXXXX XXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXX gettext(u'Item') XXXXX
                    XXXX gettext(u'Description') XXXXX
                    XXXX gettext(u'Quantity') XXXXX
                    XXXX gettext(u'Price') XXXXX
                    XXXX gettext(u'Discount') XXXXX
                    XXXX gettext(u'Tax %%') XXXXX
                    XXXX gettext(u'Total') XXXXX
                    XXXX gettext(u'Delete') XXXXX
                XXXXX
            XXXXXXXX

            XXXXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXX

                    XXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'Select Product') XXXXXXXXX
                            BBB B BB BBBBBBBB
                            XXXXXXX XXXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXX

                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                               XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                               XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                               XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX

                    XXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Delete') 
                        XXXXXXXXX
                    XXXXX

                XXXXX
            XXXXXXXX

        XXXXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            X  gettext(u'Add Item') 
        XXXXXXXXX

    XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Before Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total After Discount:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total After Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX
             gettext(u'Save Quotation') 
        XXXXXXXXX
    XXXXXX

XXXXXXX

XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

BBBBBBBB