BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXX gettext(u'Quotation Management') XXXXX

        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
            X  gettext(u'Create Quotation') 
        XXXX
    XXXXXX

    BB BBBBBBBBBB
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX

        XXXXXXX

            XXXX XXXXXX XXX XXX
            XXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search No.') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Quotation No') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Customer') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Date') XXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search Total') XXXXXXX
                XXXXXXXXX
            XXXXX

            XXXX XXXXXXX XXX
            XXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX
                XXXX gettext(u'Quotation No') XXXXX
                XXXX gettext(u'Customer') XXXXX
                XXXX gettext(u'Date') XXXXX
                XXXX gettext(u'Total') XXXXX
                XXXX gettext(u'Status') XXXXX
                XXXX gettext(u'Actions') XXXXX
            XXXXX

        XXXXXXXX

        XXXXXXX

        BBB B BB BBBBBBBBBB
        XXXX
            XXXXXXXXX

            XXXXXXXXX

            XXXXXXXXX

            XXXXXXXXX

            XXXXFFFFFFFFFFFFFXXXXX

            XXXX
                BB BBBBBBBB BB BBBBBBBBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Approved') XXXXXXX
                BBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Draft') XXXXXXX
                BBBBB
            XXXXX

            XXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Options') XXXXXXXXX

                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'View') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Print') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Download') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Edit') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
                    XXXXX
                XXXXXX
            XXXXX

        XXXXX
        BBBBBB

        XXXXXXXX
    XXXXXXXX

    BBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'No quotations available yet.') 
    XXXXXX
    BBBBB

XXXXXX

XXXXXXX
XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
X
XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X
XXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X

    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XX X XXXXXXX
                X
            XXX

        XXX

    XXX

XXX
XXXXXXXXX

BBBBBBBB