BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB

XXXXXXX

XX XXXXXXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXX
X
XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXX
    XXXXXX XX
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX X X XXX XXXX
    XXXXXXXX XXXXX
X
XXXXXXXXXXXXXX X
    XXXXXXXX XXX XXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXX
X
XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
X

XX XXXXXXX XX
XXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
X

XXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXX XXX XX
X

XXXXXXXXX X
    XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXX XXXX XXXXXXXXXXX
    XXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX

XXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Create Quotation') XXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX

    XXXX XXXXXXXXXXX XXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Quotation No:') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Quotation Date:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Customer:') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX

                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                           XXXXXXXXXXXXX gettext(u'Search customer...') X XXXXXXXXXXXXXXXXXXX

                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X  gettext(u'Add Customer') 
                XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX
            XXXXXXX gettext(u'Description:') XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Product') 
            XXXXXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXX gettext(u'Item') XXXXX
                    XXXX gettext(u'Description') XXXXX
                    XXXX gettext(u'Quantity') XXXXX
                    XXXX gettext(u'Price') XXXXX
                    XXXX gettext(u'Discount') XXXXX
                    XXXX gettext(u'Tax %%') XXXXX
                    XXXX gettext(u'Total') XXXXX
                    XXXX gettext(u'Delete') XXXXX
                XXXXX
            XXXXXXXX

            XXXXXX XXXXXXXXXXXXXXXXX

                XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX

                    XXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX
                                   XXXXXXXXXXXXXXXXXXXX
                                   XXXXXXXXXXXX
                                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                   XXXXXXXXXXXXX gettext(u'Search product...') X
                                   XXXXXXXXXXXXXXXXXXX

                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
                    XXXXX

                    XXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Delete') 
                        XXXXXXXXX
                    XXXXX
                XXXXX

            XXXXXXXX
        XXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Row') 
            XXXXXXXXX
        XXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Before Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total After Discount:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Total After Tax:') XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
             gettext(u'Save Quotation') 
        XXXXXXXXX
    XXXXXX

XXXXXXX

XXXXXX

BBBBBBBB