BBBBBBB BBBBBBBBBBBBBBBBBB
BBBBB BBBBBXXX XXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BBBB BB BBBBBBBBBBBBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
        BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
BBBBBBBB
