# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة (بالعربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة بالإنجليزية')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('commercial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('country', models.CharField(default='المملكة العربية السعودية', max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='الشارع')),
                ('building_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم المبنى')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('additional_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الإضافي')),
                ('national_address', models.TextField(blank=True, null=True, verbose_name='العنوان الوطني الكامل')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف الثابت')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='جوال الشركة')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للشركة')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='الشعار')),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم البنك')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الآيبان (IBAN)')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب')),
                ('swift_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Swift Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'معلومات الشركة',
                'verbose_name_plural': 'معلومات الشركات',
            },
        ),
    ]
