# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مركز التكلفة')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='كود مركز التكلفة')),
                ('type', models.CharField(choices=[('BRANCH', 'فرع'), ('PROJECT', 'مشروع'), ('EMPLOYEE', 'موظف'), ('SUPPLIER', 'مورد'), ('CUSTOMER', 'عميل'), ('CONTRACTOR', 'مقاول'), ('DEPARTMENT', 'إدارة'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع مركز التكلفة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('CLOSED', 'مغلق')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='accounts.company', verbose_name='الشركة')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cost_centers.costcenter', verbose_name='مركز أعلى')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='cc_uniq_name_per_company'), models.UniqueConstraint(fields=('company', 'code'), name='cc_uniq_code_per_company')],
            },
        ),
    ]
