# Generated by Django 5.2.8 on 2025-12-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الفرع')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='كود الفرع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مركز التكلفة')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='كود مركز التكلفة')),
                ('type', models.CharField(choices=[('BRANCH', 'فرع'), ('PROJECT', 'مشروع'), ('EMPLOYEE', 'موظف'), ('SUPPLIER', 'مورد'), ('CUSTOMER', 'عميل'), ('CONTRACTOR', 'مقاول'), ('DEPARTMENT', 'إدارة'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع مركز التكلفة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('CLOSED', 'مغلق')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_centers.branch', verbose_name='الفرع')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cost_centers.costcenter', verbose_name='المركز الأب')),
            ],
        ),
    ]
