# Generated by Django 5.2.8 on 2025-12-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['name'], 'verbose_name': 'مركز تكلفة', 'verbose_name_plural': 'مراكز التكلفة'},
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cost_centers.costcenter', verbose_name='مستوى مركز التكلفة (يتبع لمركز)'),
        ),
    ]
