# Generated by Django 5.2.9 on 2026-07-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZatcaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('simulation', 'Simulation'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='بيئة العمل')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل الربط')),
                ('device_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device UUID')),
                ('compliance_request_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compliance Request ID')),
                ('binary_security_token', models.TextField(blank=True, null=True, verbose_name='Binary Security Token')),
                ('secret', models.TextField(blank=True, null=True, verbose_name='Secret')),
                ('certificate', models.TextField(blank=True, null=True, verbose_name='Certificate')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='Private Key')),
                ('public_key', models.TextField(blank=True, null=True, verbose_name='Public Key')),
                ('csr', models.TextField(blank=True, null=True, verbose_name='CSR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zatca', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات هيئة الزكاة',
                'verbose_name_plural': 'إعدادات هيئة الزكاة',
            },
        ),
    ]
