# Generated by Django 5.2.9 on 2026-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zatcasettings',
            options={},
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='csr_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CSR Path'),
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='private_key_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Private Key Path'),
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='public_key_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Public Key Path'),
        ),
    ]
