# Generated by Django 5.2.9 on 2026-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatca', '0002_alter_zatcasettings_options_zatcasettings_csr_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zatcasettings',
            name='status',
            field=models.CharField(choices=[('draft', 'غير جاهز'), ('csr_created', 'تم إنشاء CSR'), ('compliance', 'اختبار الامتثال'), ('active', 'مفعل')], default='draft', max_length=20, verbose_name='حالة الربط'),
        ),
    ]
