# Generated by Django 5.2.9 on 2026-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatca', '0003_zatcasettings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zatcasettings',
            name='status',
            field=models.CharField(choices=[('draft', 'غير جاهز'), ('csr_created', 'تم إنشاء CSR'), ('compliance', 'اختبار الامتثال'), ('active', 'مفعل'), ('failed', 'فشل الربط')], default='draft', max_length=20, verbose_name='حالة الربط'),
        ),
    ]
