# Generated by Django 5.2.9 on 2026-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatca', '0004_alter_zatcasettings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zatcasettings',
            name='compliance_binary_security_token',
            field=models.TextField(blank=True, null=True, verbose_name='Compliance Binary Security Token'),
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='compliance_secret',
            field=models.TextField(blank=True, null=True, verbose_name='Compliance Secret'),
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='production_binary_security_token',
            field=models.TextField(blank=True, null=True, verbose_name='Production Binary Security Token'),
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='production_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Production Request ID'),
        ),
        migrations.AddField(
            model_name='zatcasettings',
            name='production_secret',
            field=models.TextField(blank=True, null=True, verbose_name='Production Secret'),
        ),
    ]
