# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ar', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('color_theme', models.CharField(default='light', max_length=20)),
                ('page_size', models.CharField(default='A4', max_length=20)),
                ('page_orientation', models.CharField(default='portrait', max_length=20)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
