# Generated by Django 5.2.8 on 2025-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ar', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('color_theme', models.CharField(default='light', max_length=20)),
                ('page_size', models.CharField(default='A4', max_length=20)),
                ('page_orientation', models.CharField(default='portrait', max_length=20)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
