BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBBBBBXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
