BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB
BB BBBBBBB gettext(u'Edit Product') BBBB gettext(u'Add Product') BBBBB
BBBBBBBB

BBBBB BBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXXX X
        XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXX XXXXXXXXXXX
        XXXXXXX XXXX XXXXXXXXXXX
    X

    XXXXXXXXX XXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
XXXXXXXX

XXX XXXXXXXXXXX XXXXXXXXXX
    BB BBBBBBB gettext(u'Edit Product') BBBB gettext(u'Add Product') BBBBB
XXXXX

XXXX XXXXXXXXXXX XXXXX

    XXXX XXXX XXX
    XXX XXXXXXXXXX XXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Normal Product') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Bundle Product') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Service') XXXX
        XXXXX
    XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
               XXXXXXXFFFFFFFFFFFFFFFFXX

        XXXX XXXXX XXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Product Name') XXXXXXXX
                XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                       XXXXXXXFFFFFFFFFFX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'SKU') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXX
                       XXXXXXXFFFFFFFFFFX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Category') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Category') XXXXXXXXX
                    BBB BBB BB BBBBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                            
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Purchase Price') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXFFFFFFFFFX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Sale Price') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                       XXXXXXXFFFFFFFFFX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Minimum Stock') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXFFFFFFFFFX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Low Stock Alert') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                       XXXXXXXFFFFFFFFFX
                       XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Inventory Account') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                    BBB BBB BB BBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                             X 
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Cost of Sales Account') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                    BBB BBB BB BBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                             X 
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Revenue Account') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                    BBB BBB BB BBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                             X 
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Description') XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXFFFFFFFFFFXXXXXXXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Image') XXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
                XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX
            XXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Product Components') XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBB
                XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BBB B BB BBBBBBBB
                                XXXXXXX XXXXXXXX
                                    BB BBBB BB BBBBBBBBBBBBBBXXXXXXXXBBBBBX
                                    
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Delete') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Component') 
            XXXXXXXXX

            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX
                 gettext(u'Save Product') 
            XXXXXXXXX
        XXXXXX

    XXXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX X gettext(u'Search...') XX
        XXXXXXXXXXX XXXXX
        XXXXXX XXXXXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB