BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Edit Product') BBBBBBBB

BBBBB BBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Edit Product') XXXXX

XXXX XXXXXXXXXXX XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Product Type') XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                     gettext(u'Normal Product') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                     gettext(u'Bundle Product') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX
                     gettext(u'Service') 
                XXXXXXXXX
            XXXXXXXXX
        XXXXXX

        XXXX XXXX X XXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Product Name') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'SKU') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Purchase Price') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Sale Price') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Minimum Stock') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Low Stock Alert') XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Inventory Account') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                    BBB BBB BB BBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                             X 
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Cost of Sales Account') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                    BBB BBB BB BBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                             X 
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Revenue Account') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXX gettext(u'Select Account') XXXXXXXXX
                    BBB BBB BB BBBBBBBB
                        XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                             X 
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX

        XXXXXX

        XXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Description') XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Image') XXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
                XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBXXXXXXXXXXXXBBBBBXX
            XXXX
            XXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Product Components') XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBB
                XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BBB B BB BBBBBBBB
                                XXXXXXX XXXXXXXX
                                    BB BBBB BB BBBBBBBBBBBBBBXXXXXXXXBBBBBX
                                    
                                XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                               XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Delete') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                X  gettext(u'Add Component') 
            XXXXXXXXX

            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                 gettext(u'Save Product') 
            XXXXXXXXX
        XXXXXX

    XXXXXXX

XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX X gettext(u'Search account...') XX
        XXXXXXXXXXX XXXXX
        XXXXXX XXXXXX
    XXX
XXX
XXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXX XXXXXXXX X XXXXXXX X XXXXXXX
XX

XXX XXXXXXXXXXX X XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
XX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXX XXXXXX
    XXXXXXXXXXXXX X X
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBB
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Delete') 
            XXXXXXXXX
        XXXXXX
    XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
XXX
XXXXXXXXX

BBBBBBBB