BBBB BBBB

XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Product Name') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'SKU') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Purchase Price') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Sale Price') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Minimum Stock') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Low Stock Alert') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXXXXXX gettext(u'Description') XXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXXXXXX gettext(u'Image') XXXXXXXX
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX