BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Manual Stock Adjustment') BBBBBBBB

BBBBB BBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXX
        XXXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXX XXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
    X
    XXXXXXXXXXXX XXXXX X
        XXXXX XX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXX XXXXXXXXXXXXX gettext(u'Manual Stock Adjustment') XXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    BBBBBBBBBB

    XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Product') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'Select Product') XXXXXXXXX
            BBB B BB BBBBBBBB
                XXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Current Stock') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Adjustment (+ / -)') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Final Quantity') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Type') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'Select') XXXXXXXXX
            BBB B BB BBBBBBB
                XXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBB
            XXXXXXX XXXXXXXXXXXXXX gettext(u'Other') XXXXXXXXX
        XXXXXXXXX
    XXXXXX

    XXXX XXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'New Type') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX
             gettext(u'Add New Type') 
        XXXXXXXXX
    XXXXXX

    XXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Notes') XXXXXXXX
        XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
             gettext(u'Execute') 
        XXXXXXXXX
    XXXXXX
XXXXXXX

XXXX XXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Add New Type') XXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'New Type') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Cancel') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Save') 
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX XX X

    XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX X gettext(u'Select Product') XX
        XXXXXX XXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X
            XXXXX XXXXXXXX X XXXX XXX XXX X XXXXXXX X XXX X XXXXXXX X XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX gettext(u'Enter new type first') XXX
            XXXXXXX
        X
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXX X
            XXXXXXX gettext(u'Enter new type') XXX
            XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

XXX
XXXXXXXXX
BBBBBBBB