BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Inventory Transactions Log') BBBBBBBB

BBBBB BBBBBBB
XXXX gettext(u'Inventory Transactions Log') XXXXX

XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Adjust Inventory') XXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Search...') X XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Search') XXXXXXXXX
    XXXXXXX
XXXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX gettext(u'Product') XXXXX
      XXXX gettext(u'Type') XXXXX
      XXXX gettext(u'Change') XXXXX
      XXXX gettext(u'Stock After Adjustment') XXXXX
      XXXX gettext(u'Date') XXXXX
      XXXX gettext(u'Note') XXXXX
      XXXX gettext(u'Actions') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBB BB BBBBB
    XXXX
      XXXXXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBB B BXBBBBXBBBBB
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXFFFFFFFFFFF FFFFXXXXX
      XXXXXXXXX
      XXXX
        BB BBBBBBBBBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Actions') 
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX gettext(u'Edit') XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure you want to delete this transaction?') XXXXX gettext(u'Delete') XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX gettext(u'View') XXXXXXXXX
          XXXXX
        XXXXXX
        BBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX gettext(u'View Only') XXXX
        BBBBB
      XXXXX
    XXXXX
    BBBBB
    XXXX
      XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'No data available') XXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX

XXXXXXX
XXXXXX XXX XXXXXX XX X XXXXXX XXXXX X

XX XXXXXX XXXX X XXXX XXXXXXX XX
XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX X XXXXXX XXXX X
XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX X XXXXXX XXXX X

XX XXXXXX XXXXX XXXXXX XX
XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
X

XX XXXXXXX XXXXXX XX
XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX X
    XXXXXX XXXX
    XXXXXXXXXXX XXXXXXX
X

XX XXXXXX XXXXXXXX XXXXXXX XXXXX XXX XXXXXXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXXXXXXXX
X
XXXXXXXX

BBBBBBBB

BBBBB BBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB