BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Stock Take Sheet') BBBBBBBB

BBBBB BBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXX XXX XXXXX XX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXX X XXXXXXXXXXXXX X
XXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
XXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXX X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXX XXXXXXXXXXXXX gettext(u'Stock Take Sheet') XXXXX

XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXX XXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Category') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'All Categories') XXXXXXXXX
            BBB BBB BB BBBBBBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXXX
XXXXXXX

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Stock saved successfully!') XXXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                        XXXXXXXXXX
                        XXXX gettext(u'Product') XXXXX
                        XXXX gettext(u'Category') XXXXX
                        XXXX gettext(u'Current Stock') XXXXX
                        XXXX gettext(u'Physical Count') XXXXX
                        XXXX gettext(u'Difference / Comment') XXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBB BB BBBB
                    XXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXXXX XXXXXXXXXXXXX
                                   XXXXXXXXXXXXXXXX
                                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                   XXXXXXXXXXXXX gettext(u'Enter quantity') X
                                   BB BBBBBBBBBXXXXXXXXBBBBBX
                        XXXXX
                        XXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                   XXXXXXXFFFFFFFFFFX XXXXXXXXX
                        XXXXX
                    XXXXX
                    BBBBB
                    XXXXXXX XXXXXXXXXXXX gettext(u'No products found') XXXXXXXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX

    BB BBB BBBBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Save Stock') XXXXXXXXX
    XXXXXX
    BBBBB
XXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX

    XXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXX XX XX
                XXXXX XXXX X XXXXXXXX X XXXXXXXXXXXXX

                XX XXXXX XXX XX XXXXXXXXXXXXXXXXX X X gettext(u'Matched') XX
                XXXX XX XXXXX X XX XXXXXXXXXXXXXXXXX X X gettext(u'Over by')  X X XXXXX
                XXXX XXXXXXXXXXXXXXXXX X X gettext(u'Short by')  X X XXXXXXXXXXXXXXX
            XXX
        X
    XXX

    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXX

            XXXXXXXX
                XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
                XXXXXXX XXXXXXX
                XXXXX XXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                        XXX
                    X XXXX X
                        XXXXXXX gettext(u'Error while saving') X X X XXXXXXXXXXXXXXX XX XXXXX
                    X
                XX
                XXXXXX XXXXXXXXXXXXXX
                    XXX XXX X X gettext(u'Error while saving') XX
                    XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XX XX X X XXXXXXXXXXXXXXXXXXXXXXX
                    X
                    XXXXXXXXXXX
                X
            XXX
        XXX
    X
XXX
XXXXXXXXX
BBBBBBBB