BBBB BBBB BBBBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXX XXXXXBB BBBBBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBB gettext(u'Accounting System ERP') BBBBBBBBXXXXXXXX

    XXXX XXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

XXXXXXX
XX XXXXX XXX XXXXXX XXX XXX XXXXXXXX XXXXX XX
XX XXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXX
X

XXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXX XX
X

XXXXXXXXXXXXXXX XXXX X
    XXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXX
X

XXXXXXXXXXXXXXX XXXX X
    XXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXX
X

XXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXX XXXX
X

XX XXXXX XXXXXXX XXXXX XX
XXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XX
X

XXXXXXXX XX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXX XX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXX XXXXX
X

XXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXX
X

XXXXXXXX X X
    XXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXX XX
X

XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXX XXXXXXXX
X

XX XXXXX XXXXXXX XXXXX XX
XXXXXXXXXXXXXXXX X
    XXXXX X X XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXX XX
X

XXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
X

XX XXXXX XXXXXX XXXXXX XXXXXXXX XXXXX XX
XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
X

XXXXXXXXX XXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXX XXXXX X
    XXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXX XXXXXXXXX XXXXX X
    XXXXXXXXXX XXXX
X

XXXXXXXXX XXXXX XXX
XXXXXXXXX XXXXX XX X
    XXXXXXXXXXXX XXXXXXX
X

XX XXXXXX XXXX XXXXXXXXX XX
XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXX
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
X

XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XX

XX XXXX XXXXXXX XXXXXXXX XXXXXX XXXXX XXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXX XXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXX XXXXX
    XXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
X

XXXXXXXXXXXXXX XXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
X

XX XXXX XXXXXXX XXXXX XXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXX XXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXX XXXXX
    XXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXXX XX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXX XX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXX XX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXX
X

XXXXXXXXXXXXXXXX XX
XXXXXXXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXX XXXXXX X
    XXXXXX XXXXX
X

XX XXXX XXX XXXXXXXX XXXXXX XXXXXXX XXXXX XXXX XX
XXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXX XXXXX
    XXXXX XXXXX
X

XXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXX
    XXXXXX XXXXX
X

XXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
X

XXXXXXXXXX XXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
X
XXXXXXXX

BBBBB BBBBBBBBBBBB
XXXXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX
    XXXX gettext(u'Accounting System') XXXXX
    XXXX gettext(u'ERP') XXXXX

    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Dashboard') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Human Resources') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX gettext(u'Employee Management') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Shift Management') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Employee Schedule Management') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXX XXXXXXXXX XXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX gettext(u'Attendance and Departure Log') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Leave Management') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Payroll') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Evaluation Management') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Evaluation Records Management') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Permissions') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Reports') XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXX XX XXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Point of Sale') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Point of Sale') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Sales') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX gettext(u'Customers') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sales Invoices') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sales Returns') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX gettext(u'Quotations') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Purchases') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX gettext(u'Suppliers') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Purchase Invoices') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Purchase Returns') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Purchase Orders') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Products') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX gettext(u'Product List') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Product Categories') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Manual Stock Adjustment') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Stock Movement Log') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Stock Count Sheet') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Inventory Management') XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Accounting') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Journal Entries') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Chart of Accounts') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Cost Centers') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Cost Center Tree') XXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Payments') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Receipt Vouchers') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Payment Vouchers') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reports') XXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Company Settings') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBB
    XXXXXX
XXXXXX

XXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXX X XXXX
X

XX XXXXXXX XXXXXX XXXX XXXXX XXXXXXXXXX XX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXX X XXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXX X XXXXXXXXXXXXXXXXXX XXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX X XXXX X XXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXX X XXX X XXXX
        XXX
    XXX
XXX

XX XXXXX XXXXXXXXXX XX XXXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
    X
XX XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BBBBB BBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Profile') XX
    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Profile') XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Username') X XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Company') X
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        
                    BBBB
                         gettext(u'Not Specified') 
                    BBBBB
                XXXX

                XXXX X XXXXXXXX XXXXXX XXX
                XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                        BBBBBBBBBB
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX

                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBXXXXXXXXXXXXXXXXBBBBBXX
                            XX
                        XXXXXXXXX

                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBXXXXXXXXXXXXXXXXBBBBBXX
                            XX
                        XXXXXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBBBBB BB BBBBBBBBBBB
            BB BBBBBBBBBBB
                XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX gettext(u'Edit Image') XXXX
            BBBB
                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX gettext(u'Edit Image') XXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Logout') 
            XXXXXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXX
XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXX gettext(u'Help') XX
    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX
XXXX

XXXXXXXX
XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX
XXX XXXXXXXXX X XX XXXXXXXXX X XX XXXXXXXX X XXXXXX XXXXXXX X XXXXXX

XX XXXXXXX XXXXXXXX
XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXXXXXXXXX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXX X XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXX XXXX XXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
XXX

XX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXX X XXXXX
    XXXXXXX X XXXXXX

    XX XXXXXXX X
        XXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    X XXXX X
        XXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXX

    XXXXXXX X XXXXX

    XXXXX XXXXXX X XXXXXXXXXX X XXXXXXXXXXX

    XX XXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X XXXX X
        XXXXX XXXXXXX X XXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX X XXX X XXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXX
    XXXXXXXX X XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

    XXXXX XXXXXXXXX X XXXXX
        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        X XXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX

    XXXXXXXXXXXXX XX X XXXXXXX X XXXXXX XX XXXX
XXX

XX XXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XX
XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXX XXXXXXXXX X XX XXXXXXXXX X XX XXXXXXXX X XXXXXX

XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXXXXXX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXX  X XXXXXXX  X XXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXX X XXXXX
    XXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXX  X XXXXXXXXXX X XXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXX
    XXXXXXXX X XXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX
        XXXX  XXXXXXXXXXXXXXXX
    XXXX
XXX
XXXXXXXXX

BBBBB

XXXXXXX
XXXXXXX