BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXX
XXXXXX
XXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXXBBBBB BBBBBXXXBBBBBBBBXXXXXXXX

XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
    XXXXXXXXX
    XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
  X

  XXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
  X

  XXXXXX XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXX
  X

  XX XXXXXXXXXX XXXX XXXX XXXXXX XX
  XXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXX
  X

  XXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
  X

  XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
  X
  XXXXXX
    XXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
  X

  XXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXXXXXXXXXXXXX
  X
  XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XX
  XXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
  X

  XX XXXX XXXX XXXX XX
  XXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  X

  XXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
  X

  XXXXX XXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X X XXX XXXXXXXXXXXXXXXXXXXX
  X

  XXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    XXXXXXXXX
  X
  XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X

  XXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXX

  XXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
  X
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XX XXXXXX XXXX XX
  XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
  X
XXXXXXXX

BBBBB BBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
BBBBB BBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX
