# Generated by Django 5.2.9 on 2026-07-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='رقم الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الحساب بالإنجليزية')),
                ('account_type', models.CharField(choices=[('ASSET', 'أصول'), ('LIABILITY', 'خصوم'), ('EQUITY', 'حقوق ملكية'), ('REVENUE', 'إيرادات'), ('EXPENSE', 'مصروفات')], max_length=20, verbose_name='نوع الحساب الأساسي')),
                ('nature', models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], max_length=10, verbose_name='الطبيعة المحاسبية')),
                ('is_group', models.BooleanField(default=False, help_text='لا يقبل قيود مباشرة', verbose_name='حساب تجميعي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفول')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='وسوم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.company', verbose_name='الشركة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود مركز التكلفة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم مركز التكلفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter', verbose_name='مركز التكلفة الأب')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.PositiveIntegerField(unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='تاريخ القيد')),
                ('description', models.TextField(blank=True, verbose_name='البيان')),
                ('source_type', models.CharField(choices=[('manual', 'قيد يدوي'), ('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات')], default='manual', max_length=50, verbose_name='مصدر القيد')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المصدر')),
                ('posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_journal_entries', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'القيود اليومية',
                'ordering': ['-date', '-entry_no'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='بيان السطر')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_account_code_per_company'),
        ),
    ]
