# Generated by Django 5.2.9 on 2026-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_payment_method',
            field=models.BooleanField(default=False, verbose_name='طريقة دفع'),
        ),
    ]
