# Generated by Django 5.2.9 on 2026-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_fix_journal_entry_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='unique_company_entry_no',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_no',
            field=models.PositiveIntegerField(unique=True, verbose_name='رقم القيد'),
        ),
    ]
