# Generated by Django 5.2.9 on 2026-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_journalentry_unique_company_entry_no_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_no',
            field=models.PositiveIntegerField(verbose_name='رقم القيد'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'entry_no'), name='unique_journal_entry_no_per_company'),
        ),
    ]
