# Generated by Django 5.2.8 on 2025-12-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centers', '0002_alter_branch_options_alter_costcenter_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='header_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='cost_centers.costcenter', verbose_name='مركز التكلفة (رأس الفاتورة)'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='cost_centers.costcenter', verbose_name='مركز التكلفة'),
        ),
    ]
