# Generated by Django 5.2.9 on 2026-08-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_invoice_created_by'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='pos_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='pos.invoice'),
        ),
    ]
