# Generated by Django 5.2.8 on 2025-12-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesinvoice_header_cost_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='header_cost_center',
        ),
    ]
