# Generated by Django 5.2.9 on 2026-08-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_returninvoice_pos_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
