# Generated by Django 5.2.9 on 2026-01-01 12:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_returninvoice_options_alter_returnitem_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المسدد'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مسددة'), ('partial', 'مسددة جزئياً'), ('paid', 'مسددة بالكامل')], default='unpaid', max_length=10, verbose_name='حالة السداد'),
        ),
    ]
