# Generated by Django 5.2.9 on 2026-01-03 12:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoice_paid_amount_salesinvoice_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returninvoice',
            name='tax_value',
        ),
        migrations.RemoveField(
            model_name='returninvoice',
            name='total_after_discount',
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='date_return',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='sales.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='return_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='total_after_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='total_before_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
