# Generated by Django 5.2.9 on 2026-01-03 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_returninvoice_tax_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninvoice',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
