# Generated by Django 5.2.8 on 2025-12-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_products', to='accounting.account', verbose_name='حساب تكلفة المبيعات'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_products', to='accounting.account', verbose_name='حساب المخزون'),
        ),
        migrations.AddField(
            model_name='product',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_products', to='accounting.account', verbose_name='حساب الإيرادات'),
        ),
    ]
