# Generated by Django 5.2.9 on 2026-01-09 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_stockadjustreason_remove_product_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0)),
                ('matched_items', models.IntegerField(default=0)),
                ('mismatched_items', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('MATCH', 'مطابق'), ('PARTIAL', 'مطابق جزئياً'), ('MISMATCH', 'غير مطابق')], default='MATCH', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_takes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=2, max_digits=14)),
                ('physical_qty', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diff_qty', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_items', to='products.product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.stocktake')),
            ],
        ),
    ]
