# Generated by Django 5.2.9 on 2026-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stocktake_stocktakeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('normal', 'منتج عادي'), ('bundle', 'منتج مركب'), ('service', 'خدمة')], default='normal', max_length=20),
        ),
    ]
