# Generated by Django 5.2.9 on 2026-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_entry_no_and_more'),
        ('accounts', '0001_initial'),
        ('products', '0006_product_barcode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'barcode'), name='uniq_product_barcode_per_company'),
        ),
    ]
