# Generated by Django 5.2.9 on 2026-10-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_uniq_product_barcode_per_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scale_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='كود الميزان'),
        ),
    ]
